function opts = Plot_Defaults()
%PLOT_DEFAULTS Central defaults for plotting utilities.
%   opts = Plot_Defaults() returns a struct of reusable defaults used by
%   Plot_Format, Legend_Format, Plot_Saver, and Plot_Format_And_Save.

    opts.FontSizes        = {20, 20, 25};
    opts.AxisLineWidth    = 1.2;
    opts.GridLineWidth    = 1.0;
    opts.FigureColor      = [1, 1, 1];
    opts.GridColor        = [0, 0, 0];
    opts.TickInterpreter  = "latex";

    opts.Legend = struct( ...
        "FontSize", 20, ...
        "Orientation", "vertical", ...
        "NumColumns", 1, ...
        "NumRows", [], ... % computed if empty
        "AutoLocation", true, ...
        "LocationOverride", "best", ...
        "BoxOption", "off", ...
        "Padding", 0.5 ...
    );

    opts.ResolutionPresets = struct( ...
        "Laptop",    600, ...
        "Secondary", 450, ...
        "High",      600, ...
        "Low",       180 ...
    );
end
