% ========================================================================
% TSUNAMI VORTEX SIMULATION - UNIFIED USER INTERFACE
% ========================================================================
% Purpose:
%   Comprehensive GUI for configuring and launching numerical simulations
%   Self-contained interface with integrated monitoring and visualization
%
% Features:
%   • Method Selection (Finite Difference, Finite Volume, Spectral)
%   • Mode Configuration (Evolution, Convergence, Sweep, Animation, Experimentation)
%   • Initial Condition Designer (Default presets + custom configuration)
%   • Live Execution Monitor (CPU, Memory, Iteration tracking)
%   • Convergence Monitor (Real-time error decay, mesh refinement tracking)
%   • Parameter Validation & Export to Analysis.m
%
% Usage:
%   >> UI_Controller
%   % Configure settings in GUI, then click "Launch Simulation"
%
% Architecture:
%   The UI generates a configuration structure that is passed to Analysis.m
%   All monitors are embedded in the UI (no separate windows)
%
% ========================================================================

function UI_Controller()
    % Main UI entry point
    close all;
    
    %% Initialize UI State
    ui = struct();
    ui.config = initialize_default_config();
    ui.handles = struct();
    
    %% Create Main Figure
    ui.fig = uifigure('Name', 'Tsunami Vortex Simulation Control Panel', ...
        'Position', [100 100 1400 900], ...
        'Color', [0.94 0.94 0.94]);
    
    %% Create Tab Group
    ui.tab_group = uitabgroup(ui.fig, 'Position', [10 10 1380 880]);
    
    % Tab 1: Method & Mode Selection
    ui.tabs.method = uitab(ui.tab_group, 'Title', '1. Method & Mode');
    create_method_mode_tab(ui.tabs.method, ui);
    
    % Tab 2: Initial Conditions
    ui.tabs.ic = uitab(ui.tab_group, 'Title', '2. Initial Conditions');
    create_ic_tab(ui.tabs.ic, ui);
    
    % Tab 3: Numerical Parameters
    ui.tabs.params = uitab(ui.tab_group, 'Title', '3. Numerical Parameters');
    create_parameters_tab(ui.tabs.params, ui);
    
    % Tab 4: Convergence Settings
    ui.tabs.convergence = uitab(ui.tab_group, 'Title', '4. Convergence Study');
    create_convergence_tab(ui.tabs.convergence, ui);
    
    % Tab 5: Sustainability & Monitoring
    ui.tabs.sustainability = uitab(ui.tab_group, 'Title', '5. Sustainability Tracking');
    create_sustainability_tab(ui.tabs.sustainability, ui);
    
    % Tab 6: Live Execution Monitor
    ui.tabs.exec_monitor = uitab(ui.tab_group, 'Title', '📊 Execution Monitor');
    create_execution_monitor_tab(ui.tabs.exec_monitor, ui);
    
    % Tab 7: Convergence Monitor
    ui.tabs.conv_monitor = uitab(ui.tab_group, 'Title', '📈 Convergence Monitor');
    create_convergence_monitor_tab(ui.tabs.conv_monitor, ui);
    
    %% Launch Button (always visible at bottom)
    ui.btn_launch = uibutton(ui.fig, 'push', ...
        'Position', [1100 20 250 50], ...
        'Text', '🚀 Launch Simulation', ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.2 0.7 0.3], ...
        'FontColor', 'white', ...
        'ButtonPushedFcn', @(btn,event) launch_simulation(ui));
    
    ui.btn_export = uibutton(ui.fig, 'push', ...
        'Position', [820 20 250 50], ...
        'Text', '💾 Export Configuration', ...
        'FontSize', 14, ...
        'BackgroundColor', [0.3 0.5 0.8], ...
        'FontColor', 'white', ...
        'ButtonPushedFcn', @(btn,event) export_configuration(ui));
    
    % Store UI handle in app data for global access
    setappdata(ui.fig, 'UI_State', ui);
end

%% ========================================================================
%% TAB 1: METHOD & MODE SELECTION
%% ========================================================================
function create_method_mode_tab(parent, ui)
    % Method Selection Panel
    panel_method = uipanel(parent, 'Title', 'Analysis Method', ...
        'Position', [20 550 660 280], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_method, 'Position', [20 220 600 25], ...
        'Text', 'Select the numerical method for spatial discretization:', ...
        'FontSize', 12);
    
    ui.handles.method_group = uibuttongroup(panel_method, 'Position', [20 50 600 170]);
    
    uiradiobutton(ui.handles.method_group, 'Position', [20 120 550 30], ...
        'Text', 'Finite Difference (Standard - 2nd Order Central)', 'FontSize', 11, 'Value', 1);
    uiradiobutton(ui.handles.method_group, 'Position', [20 80 550 30], ...
        'Text', 'Finite Volume (Conservative Formulation)', 'FontSize', 11);
    uiradiobutton(ui.handles.method_group, 'Position', [20 40 550 30], ...
        'Text', 'Spectral (Fourier-based - High Accuracy)', 'FontSize', 11);
    
    % Mode Selection Panel
    panel_mode = uipanel(parent, 'Title', 'Simulation Mode', ...
        'Position', [700 550 660 280], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_mode, 'Position', [20 220 600 25], ...
        'Text', 'Select the type of analysis to perform:', ...
        'FontSize', 12);
    
    ui.handles.mode_dropdown = uidropdown(panel_mode, ...
        'Position', [20 180 600 30], ...
        'Items', {'Evolution - Single Simulation', ...
                  'Convergence - Mesh Refinement Study', ...
                  'Sweep - Parameter Sensitivity', ...
                  'Animation - High-FPS Visualization', ...
                  'Experimentation - Multi-Configuration Test'}, ...
        'Value', 'Convergence - Mesh Refinement Study', ...
        'FontSize', 11);
    
    % Mode Description Box
    ui.handles.mode_description = uitextarea(panel_mode, ...
        'Position', [20 20 600 150], ...
        'Value', get_mode_description('convergence'), ...
        'Editable', 'off', ...
        'FontSize', 10);
    
    ui.handles.mode_dropdown.ValueChangedFcn = @(dd,event) update_mode_description(ui);
    
    % Quick Start Panel
    panel_quickstart = uipanel(parent, 'Title', 'Quick Start Presets', ...
        'Position', [20 50 1340 480], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_quickstart, 'Position', [20 420 1200 25], ...
        'Text', 'Load pre-configured settings for common research scenarios:', ...
        'FontSize', 12);
    
    % Preset buttons in grid
    btn_y = 350;
    uibutton(panel_quickstart, 'push', 'Position', [20 btn_y 300 50], ...
        'Text', '🎯 Kutz Figure Replication', 'FontSize', 11, ...
        'BackgroundColor', [0.9 0.95 1], ...
        'ButtonPushedFcn', @(~,~) load_preset(ui, 'kutz'));
    
    uibutton(panel_quickstart, 'push', 'Position', [340 btn_y 300 50], ...
        'Text', '📐 Convergence Study (128→512)', 'FontSize', 11, ...
        'BackgroundColor', [0.95 0.95 1], ...
        'ButtonPushedFcn', @(~,~) load_preset(ui, 'convergence'));
    
    uibutton(panel_quickstart, 'push', 'Position', [660 btn_y 300 50], ...
        'Text', '🔍 Parameter Sweep (Viscosity)', 'FontSize', 11, ...
        'BackgroundColor', [1 0.95 0.9], ...
        'ButtonPushedFcn', @(~,~) load_preset(ui, 'sweep_viscosity'));
    
    uibutton(panel_quickstart, 'push', 'Position', [980 btn_y 300 50], ...
        'Text', '🎬 High-FPS Animation (60 FPS)', 'FontSize', 11, ...
        'BackgroundColor', [0.95 1 0.95], ...
        'ButtonPushedFcn', @(~,~) load_preset(ui, 'animation'));
    
    % Preset descriptions
    ui.handles.preset_info = uitextarea(panel_quickstart, ...
        'Position', [20 20 1280 320], ...
        'Value', get_preset_descriptions(), ...
        'Editable', 'off', ...
        'FontSize', 10);
end

%% ========================================================================
%% TAB 2: INITIAL CONDITIONS
%% ========================================================================
function create_ic_tab(parent, ui)
    % Default IC Selection Panel
    panel_default = uipanel(parent, 'Title', 'Default Initial Conditions', ...
        'Position', [20 450 660 380], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_default, 'Position', [20 330 600 25], ...
        'Text', 'Select from predefined vortex configurations:', ...
        'FontSize', 12);
    
    ui.handles.ic_dropdown = uidropdown(panel_default, ...
        'Position', [20 290 600 30], ...
        'Items', {'Stretched Gaussian (Kutz)', 'Vortex Blob (Gaussian)', ...
                  'Vortex Pair', 'Multi-Vortex', 'Counter-Rotating Pair', 'Custom'}, ...
        'Value', 'Stretched Gaussian (Kutz)', ...
        'FontSize', 11, ...
        'ValueChangedFcn', @(~,~) update_ic_preview(ui));
    
    % IC Coefficient Configuration
    uilabel(panel_default, 'Position', [20 250 200 25], ...
        'Text', 'Coefficient 1 (X-stretch):', 'FontSize', 11);
    ui.handles.ic_coeff1 = uieditfield(panel_default, 'numeric', ...
        'Position', [230 250 150 25], 'Value', 2.0, ...
        'ValueChangedFcn', @(~,~) update_ic_preview(ui));
    
    uilabel(panel_default, 'Position', [20 210 200 25], ...
        'Text', 'Coefficient 2 (Y-stretch):', 'FontSize', 11);
    ui.handles.ic_coeff2 = uieditfield(panel_default, 'numeric', ...
        'Position', [230 210 150 25], 'Value', 0.2, ...
        'ValueChangedFcn', @(~,~) update_ic_preview(ui));
    
    % IC Preview Panel
    ui.handles.ic_preview_axes = uiaxes(panel_default, ...
        'Position', [20 20 600 180]);
    title(ui.handles.ic_preview_axes, 'Initial Condition Preview');
    xlabel(ui.handles.ic_preview_axes, 'X');
    ylabel(ui.handles.ic_preview_axes, 'Y');
    
    % Custom IC Configuration Panel
    panel_custom = uipanel(parent, 'Title', 'Custom Initial Condition Designer', ...
        'Position', [700 450 660 380], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_custom, 'Position', [20 330 600 25], ...
        'Text', 'Define custom vortex configuration (Advanced):', ...
        'FontSize', 12);
    
    ui.handles.custom_ic_code = uitextarea(panel_custom, ...
        'Position', [20 80 600 240], ...
        'Value', {'% Custom IC function (MATLAB code)', ...
                  '% Available variables: X, Y (meshgrid)', ...
                  'omega = 2*exp(-((X-5).^2 + (Y-5).^2)/1);'}, ...
        'FontSize', 10);
    
    uibutton(panel_custom, 'push', ...
        'Position', [20 30 280 40], ...
        'Text', '🔄 Refresh Preview', ...
        'FontSize', 11, ...
        'ButtonPushedFcn', @(~,~) update_ic_preview(ui));
    
    uibutton(panel_custom, 'push', ...
        'Position', [320 30 280 40], ...
        'Text', '💾 Save as Preset', ...
        'FontSize', 11, ...
        'ButtonPushedFcn', @(~,~) save_custom_ic(ui));
    
    % IC Theory Panel
    panel_theory = uipanel(parent, 'Title', 'Initial Condition Theory', ...
        'Position', [20 50 1340 380], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.ic_theory = uitextarea(panel_theory, ...
        'Position', [20 20 1280 330], ...
        'Value', get_ic_theory_text(), ...
        'Editable', 'off', ...
        'FontSize', 10);
    
    % Initialize preview
    update_ic_preview(ui);
end

%% ========================================================================
%% TAB 3: NUMERICAL PARAMETERS
%% ========================================================================
function create_parameters_tab(parent, ui)
    % Domain Parameters Panel
    panel_domain = uipanel(parent, 'Title', 'Computational Domain', ...
        'Position', [20 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    % Grid Layout for domain parameters
    create_param_field(panel_domain, 'Domain Length X (Lx):', 20, 170, ui, 'Lx', 10, '[m]');
    create_param_field(panel_domain, 'Domain Length Y (Ly):', 20, 130, ui, 'Ly', 10, '[m]');
    create_param_field(panel_domain, 'Grid Points X (Nx):', 20, 90, ui, 'Nx', 128, '[-]');
    create_param_field(panel_domain, 'Grid Points Y (Ny):', 20, 50, ui, 'Ny', 128, '[-]');
    
    % Physical Parameters Panel
    panel_physical = uipanel(parent, 'Title', 'Physical Properties', ...
        'Position', [700 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    create_param_field(panel_physical, 'Kinematic Viscosity (ν):', 20, 170, ui, 'nu', 1e-6, '[m²/s]');
    create_param_field(panel_physical, 'Grid Spacing (δ):', 20, 130, ui, 'delta', 2.0, '[m]');
    
    ui.handles.use_explicit_delta = uicheckbox(panel_physical, ...
        'Position', [350 130 250 25], ...
        'Text', 'Use explicit δ', 'Value', 1, 'FontSize', 10);
    
    % Time Integration Panel
    panel_time = uipanel(parent, 'Title', 'Time Integration', ...
        'Position', [20 350 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    create_param_field(panel_time, 'Time Step (dt):', 20, 170, ui, 'dt', 0.01, '[s]');
    create_param_field(panel_time, 'Final Time (Tfinal):', 20, 130, ui, 'Tfinal', 8.0, '[s]');
    create_param_field(panel_time, 'Number of Snapshots:', 20, 90, ui, 'num_snapshots', 9, '[-]');
    
    % CFL indicator
    ui.handles.cfl_indicator = uilabel(panel_time, ...
        'Position', [20 50 600 30], ...
        'Text', 'CFL Number: Computing...', ...
        'FontSize', 11, 'FontWeight', 'bold');
    
    % Visualization Parameters Panel
    panel_vis = uipanel(parent, 'Title', 'Visualization & Output', ...
        'Position', [700 350 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.live_preview = uicheckbox(panel_vis, ...
        'Position', [20 180 300 25], ...
        'Text', 'Enable Live Preview', 'Value', 0, 'FontSize', 11);
    
    ui.handles.create_animations = uicheckbox(panel_vis, ...
        'Position', [20 145 300 25], ...
        'Text', 'Generate Animations', 'Value', 1, 'FontSize', 11);
    
    uilabel(panel_vis, 'Position', [20 110 150 25], ...
        'Text', 'Animation Format:', 'FontSize', 10);
    ui.handles.anim_format = uidropdown(panel_vis, ...
        'Position', [180 110 200 25], ...
        'Items', {'GIF', 'MP4', 'AVI'}, 'Value', 'GIF', 'FontSize', 10);
    
    uilabel(panel_vis, 'Position', [20 75 150 25], ...
        'Text', 'Frame Rate (FPS):', 'FontSize', 10);
    ui.handles.anim_fps = uieditfield(panel_vis, 'numeric', ...
        'Position', [180 75 100 25], 'Value', 30);
    
    uilabel(panel_vis, 'Position', [20 40 150 25], ...
        'Text', 'Colormap:', 'FontSize', 10);
    ui.handles.colormap = uidropdown(panel_vis, ...
        'Position', [180 40 200 25], ...
        'Items', {'turbo', 'jet', 'parula', 'hot', 'viridis', 'gray'}, ...
        'Value', 'turbo', 'FontSize', 10);
    
    % Validation Panel
    panel_validation = uipanel(parent, 'Title', 'Parameter Validation & Stability', ...
        'Position', [20 50 1340 280], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.validation_display = uitextarea(panel_validation, ...
        'Position', [20 20 1280 230], ...
        'Value', {'Parameter validation will appear here...', ...
                  'Click "Validate Parameters" to check stability conditions.'}, ...
        'Editable', 'off', ...
        'FontSize', 10);
    
    uibutton(parent, 'push', ...
        'Position', [1100 10 250 30], ...
        'Text', '✓ Validate Parameters', ...
        'FontSize', 12, ...
        'ButtonPushedFcn', @(~,~) validate_parameters(ui));
end

%% ========================================================================
%% TAB 4: CONVERGENCE STUDY SETTINGS
%% ========================================================================
function create_convergence_tab(parent, ui)
    % Convergence Strategy Panel
    panel_strategy = uipanel(parent, 'Title', 'Convergence Strategy', ...
        'Position', [20 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_strategy, 'Position', [20 180 600 25], ...
        'Text', 'Select convergence study methodology:', ...
        'FontSize', 12);
    
    ui.handles.conv_strategy = uidropdown(panel_strategy, ...
        'Position', [20 140 600 30], ...
        'Items', {'Richardson Extrapolation (Standard)', ...
                  'Adaptive Physical Quantity', ...
                  'Agent-Guided Refinement', ...
                  'Binary Search with Bracketing'}, ...
        'Value', 'Agent-Guided Refinement', ...
        'FontSize', 11);
    
    create_param_field(panel_strategy, 'Coarse Grid (N_start):', 20, 100, ui, 'conv_N_coarse', 64, '');
    create_param_field(panel_strategy, 'Fine Grid (N_max):', 20, 60, ui, 'conv_N_max', 512, '');
    create_param_field(panel_strategy, 'Tolerance:', 20, 20, ui, 'conv_tol', 0.01, '(1%)');
    
    % Convergence Criterion Panel
    panel_criterion = uipanel(parent, 'Title', 'Convergence Criterion', ...
        'Position', [700 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_criterion, 'Position', [20 180 600 25], ...
        'Text', 'Error metric for convergence assessment:', ...
        'FontSize', 12);
    
    ui.handles.conv_criterion = uidropdown(panel_criterion, ...
        'Position', [20 140 600 30], ...
        'Items', {'L2 Relative Error', 'L2 Absolute Error', 'L∞ Relative Error', ...
                  'Max Vorticity', 'Energy Dissipation', 'Auto (Physical Quantity)'}, ...
        'Value', 'L2 Relative Error', ...
        'FontSize', 11);
    
    ui.handles.conv_save_iterations = uicheckbox(panel_criterion, ...
        'Position', [20 100 300 25], ...
        'Text', 'Save iteration figures', 'Value', 1, 'FontSize', 11);
    
    ui.handles.conv_mesh_visuals = uicheckbox(panel_criterion, ...
        'Position', [20 65 300 25], ...
        'Text', 'Generate mesh visualizations', 'Value', 1, 'FontSize', 11);
    
    ui.handles.conv_agent_enabled = uicheckbox(panel_criterion, ...
        'Position', [20 30 300 25], ...
        'Text', 'Enable agent-guided refinement', 'Value', 1, 'FontSize', 11);
    
    % Agent Configuration Panel
    panel_agent = uipanel(parent, 'Title', 'Agent-Guided Refinement Settings', ...
        'Position', [20 350 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    uilabel(panel_agent, 'Position', [20 180 250 25], ...
        'Text', 'Error Weight:', 'FontSize', 11);
    ui.handles.agent_weight_error = uieditfield(panel_agent, 'numeric', ...
        'Position', [280 180 100 25], 'Value', 0.6, 'Limits', [0 1]);
    
    uilabel(panel_agent, 'Position', [20 145 250 25], ...
        'Text', 'Cost Weight:', 'FontSize', 11);
    ui.handles.agent_weight_cost = uieditfield(panel_agent, 'numeric', ...
        'Position', [280 145 100 25], 'Value', 0.25, 'Limits', [0 1]);
    
    uilabel(panel_agent, 'Position', [20 110 250 25], ...
        'Text', 'Vorticity Weight:', 'FontSize', 11);
    ui.handles.agent_weight_vorticity = uieditfield(panel_agent, 'numeric', ...
        'Position', [280 110 100 25], 'Value', 0.15, 'Limits', [0 1]);
    
    ui.handles.agent_normalize_weights = uilabel(panel_agent, ...
        'Position', [20 75 600 25], ...
        'Text', '✓ Weights will be normalized to sum = 1.0', ...
        'FontSize', 10, 'FontColor', [0 0.6 0]);
    
    % Advanced Convergence Panel
    panel_advanced = uipanel(parent, 'Title', 'Advanced Convergence Options', ...
        'Position', [700 350 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.conv_binary = uicheckbox(panel_advanced, ...
        'Position', [20 180 300 25], ...
        'Text', 'Enable binary search', 'Value', 1, 'FontSize', 11);
    
    ui.handles.conv_use_adaptive = uicheckbox(panel_advanced, ...
        'Position', [20 145 300 25], ...
        'Text', 'Use Richardson adaptive search', 'Value', 1, 'FontSize', 11);
    
    ui.handles.conv_enable_bracketing = uicheckbox(panel_advanced, ...
        'Position', [20 110 300 25], ...
        'Text', 'Enable bracketing fallback', 'Value', 0, 'FontSize', 11);
    
    create_param_field(panel_advanced, 'Max Adaptive Jumps:', 20, 70, ui, 'conv_max_jumps', 5, '');
    create_param_field(panel_advanced, 'Bracket Factor:', 20, 30, ui, 'conv_bracket_factor', 2, '');
    
    % Convergence Info Panel
    panel_info = uipanel(parent, 'Title', 'Convergence Study Information', ...
        'Position', [20 50 1340 280], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.conv_info = uitextarea(panel_info, ...
        'Position', [20 20 1280 230], ...
        'Value', get_convergence_info_text(), ...
        'Editable', 'off', ...
        'FontSize', 10);
end

%% ========================================================================
%% TAB 5: SUSTAINABILITY TRACKING
%% ========================================================================
function create_sustainability_tab(parent, ui)
    % Energy Monitoring Panel
    panel_energy = uipanel(parent, 'Title', 'Energy Monitoring Configuration', ...
        'Position', [20 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.sustainability_enabled = uicheckbox(panel_energy, ...
        'Position', [20 180 400 25], ...
        'Text', 'Enable Hardware Energy Monitoring', 'Value', 1, 'FontSize', 12, ...
        'FontWeight', 'bold');
    
    uilabel(panel_energy, 'Position', [20 140 250 25], ...
        'Text', 'Sample Interval (seconds):', 'FontSize', 11);
    ui.handles.sustainability_interval = uieditfield(panel_energy, 'numeric', ...
        'Position', [280 140 100 25], 'Value', 0.5, 'Limits', [0.1 10]);
    
    ui.handles.track_mode_separately = uicheckbox(panel_energy, ...
        'Position', [20 105 400 25], ...
        'Text', 'Separate logs per mode', 'Value', 1, 'FontSize', 11);
    
    ui.handles.track_setup_vs_study = uicheckbox(panel_energy, ...
        'Position', [20 70 400 25], ...
        'Text', 'Track setup vs. study phases', 'Value', 1, 'FontSize', 11);
    
    ui.handles.use_icue_integration = uicheckbox(panel_energy, ...
        'Position', [20 35 400 25], ...
        'Text', 'Enable Corsair iCUE RGB feedback', 'Value', 0, 'FontSize', 11);
    
    % Sustainability Analysis Panel
    panel_analysis = uipanel(parent, 'Title', 'Post-Simulation Analysis', ...
        'Position', [700 600 660 230], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.sustainability_build_model = uicheckbox(panel_analysis, ...
        'Position', [20 180 400 25], ...
        'Text', 'Build Energy Scaling Model (E = A·C^α)', 'Value', 0, 'FontSize', 11);
    
    ui.handles.sustainability_auto_compare = uicheckbox(panel_analysis, ...
        'Position', [20 145 400 25], ...
        'Text', 'Auto-compare multi-run results', 'Value', 0, 'FontSize', 11);
    
    ui.handles.post_energy_analysis = uicheckbox(panel_analysis, ...
        'Position', [20 110 400 25], ...
        'Text', 'Generate energy report after simulation', 'Value', 0, 'FontSize', 11);
    
    uilabel(panel_analysis, 'Position', [20 70 250 25], ...
        'Text', 'Output Directory:', 'FontSize', 11);
    ui.handles.sustainability_output_dir = uieditfield(panel_analysis, 'text', ...
        'Position', [20 40 600 25], ...
        'Value', fullfile(pwd, '..', 'Results', 'Sustainability'));
    
    % Sustainability Info Panel
    panel_sus_info = uipanel(parent, 'Title', 'Sustainability Tracking Overview', ...
        'Position', [20 50 1340 530], 'FontSize', 14, 'FontWeight', 'bold');
    
    ui.handles.sustainability_info = uitextarea(panel_sus_info, ...
        'Position', [20 20 1280 480], ...
        'Value', get_sustainability_info_text(), ...
        'Editable', 'off', ...
        'FontSize', 10);
end

%% ========================================================================
%% TAB 6: LIVE EXECUTION MONITOR (EMBEDDED)
%% ========================================================================
function create_execution_monitor_tab(parent, ui)
    % Create axes for live monitoring dashboard
    ui.handles.exec_monitor_panel = uipanel(parent, ...
        'Position', [10 10 1360 820], ...
        'BorderType', 'none');
    
    % Placeholder for monitor - will be populated when simulation starts
    ui.handles.exec_monitor_axes = uiaxes(ui.handles.exec_monitor_panel, ...
        'Position', [20 20 1320 780]);
    
    title(ui.handles.exec_monitor_axes, 'Live Execution Monitor', 'FontSize', 16, 'FontWeight', 'bold');
    text(ui.handles.exec_monitor_axes, 0.5, 0.5, ...
        {'Execution monitor will activate when simulation launches', '', ...
         'Displays:', '• Real-time CPU/Memory usage', '• Iteration progress', ...
         '• Phase timing', '• Performance metrics'}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 14, ...
        'Units', 'normalized');
    
    ui.handles.exec_monitor_axes.XTick = [];
    ui.handles.exec_monitor_axes.YTick = [];
    box(ui.handles.exec_monitor_axes, 'on');
end

%% ========================================================================
%% TAB 7: CONVERGENCE MONITOR (EMBEDDED)
%% ========================================================================
function create_convergence_monitor_tab(parent, ui)
    % Create panel for convergence monitoring
    ui.handles.conv_monitor_panel = uipanel(parent, ...
        'Position', [10 10 1360 820], ...
        'BorderType', 'none');
    
    % Placeholder axes - will be populated during convergence study
    ui.handles.conv_monitor_axes = uiaxes(ui.handles.conv_monitor_panel, ...
        'Position', [20 20 1320 780]);
    
    title(ui.handles.conv_monitor_axes, 'Convergence Monitor', 'FontSize', 16, 'FontWeight', 'bold');
    text(ui.handles.conv_monitor_axes, 0.5, 0.5, ...
        {'Convergence monitor will activate during convergence study', '', ...
         'Displays:', '• Error decay vs. iteration', '• Error vs. mesh size', ...
         '• Peak vorticity stabilization', '• Predicted convergence point'}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontSize', 14, ...
        'Units', 'normalized');
    
    ui.handles.conv_monitor_axes.XTick = [];
    ui.handles.conv_monitor_axes.YTick = [];
    box(ui.handles.conv_monitor_axes, 'on');
end

%% ========================================================================
%% HELPER FUNCTIONS
%% ========================================================================

function create_param_field(parent, label_text, x, y, ui, field_name, default_val, unit_text)
    uilabel(parent, 'Position', [x y 200 25], ...
        'Text', label_text, 'FontSize', 11);
    ui.handles.(field_name) = uieditfield(parent, 'numeric', ...
        'Position', [x+210 y 120 25], 'Value', default_val);
    uilabel(parent, 'Position', [x+340 y 80 25], ...
        'Text', unit_text, 'FontSize', 10, 'FontColor', [0.5 0.5 0.5]);
end

function config = initialize_default_config()
    % Initialize default configuration matching Analysis.m
    config = struct();
    config.method = 'Finite Difference';
    config.mode = 'convergence';
    config.ic_type = 'stretched_gaussian';
    config.ic_coeff = [2.0, 0.2];
    % Add all other default parameters...
end

function desc = get_mode_description(mode)
    descriptions = struct();
    descriptions.evolution = {'EVOLUTION MODE:', '', ...
        'Single simulation run for visualization and validation.', ...
        '• Low computational cost', '• Quick results', ...
        '• Ideal for parameter exploration', '• Recreate Kutz figures'};
    descriptions.convergence = {'CONVERGENCE MODE:', '', ...
        'Multi-stage adaptive mesh refinement study.', ...
        '• Agent-guided mesh selection', '• Richardson extrapolation', ...
        '• Automated convergence detection', '• Production-quality mesh'};
    descriptions.sweep = {'SWEEP MODE:', '', ...
        'Systematic parameter sensitivity analysis.', ...
        '• Vary viscosity, time step, or IC parameters', ...
        '• Uses converged mesh from prior study', '• Comparative analysis'};
    descriptions.animation = {'ANIMATION MODE:', '', ...
        'High frame-rate visualization generation.', ...
        '• 60+ FPS animations', '• Publication quality', '• Multiple formats (GIF/MP4/AVI)'};
    descriptions.experimentation = {'EXPERIMENTATION MODE:', '', ...
        'Multi-configuration testing framework.', ...
        '• Test multiple IC types', '• Coefficient sweeps', '• Comparative metrics'};
    
    if isfield(descriptions, mode)
        desc = descriptions.(mode);
    else
        desc = {'Select a mode to see description'};
    end
end

function text = get_preset_descriptions()
    text = {
        '═══════════════════════════════════════════════════════════════════════════════', ...
        'PRESET DESCRIPTIONS:', ...
        '═══════════════════════════════════════════════════════════════════════════════', ...
        '', ...
        '🎯 KUTZ FIGURE REPLICATION:', ...
        '   • Mode: Evolution', ...
        '   • Method: Finite Difference', ...
        '   • IC: Stretched Gaussian [2.0, 0.2]', ...
        '   • Grid: 128×128, Tfinal=8s', ...
        '   • Purpose: Reproduce results from Kutz textbook', ...
        '', ...
        '📐 CONVERGENCE STUDY (128→512):', ...
        '   • Mode: Convergence', ...
        '   • Strategy: Agent-Guided Refinement', ...
        '   • Range: N=64 (coarse) → N=512 (max)', ...
        '   • Tolerance: 1% (L2 relative error)', ...
        '   • Purpose: Find optimal mesh for production simulations', ...
        '', ...
        '🔍 PARAMETER SWEEP (VISCOSITY):', ...
        '   • Mode: Sweep', ...
        '   • Parameter: Kinematic viscosity (ν)', ...
        '   • Values: [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]', ...
        '   • Purpose: Understand flow regime transitions', ...
        '', ...
        '🎬 HIGH-FPS ANIMATION (60 FPS):', ...
        '   • Mode: Animation', ...
        '   • Format: GIF (or MP4)', ...
        '   • FPS: 60', ...
        '   • Frames: 200', ...
        '   • Purpose: Smooth visualization for presentations', ...
        '═══════════════════════════════════════════════════════════════════════════════'};
end

function text = get_ic_theory_text()
    text = {
        '═══════════════════════════════════════════════════════════════════════════════', ...
        'INITIAL CONDITION THEORY:', ...
        '═══════════════════════════════════════════════════════════════════════════════', ...
        '', ...
        '1. STRETCHED GAUSSIAN (Kutz Default):', ...
        '   ω(x,y,0) = exp(-(c₁·x)² - (c₂·y)²)', ...
        '   • c₁: X-direction stretching coefficient (typical: 2.0)', ...
        '   • c₂: Y-direction stretching coefficient (typical: 0.2)', ...
        '   • Creates asymmetric vortex that evolves over time', ...
        '', ...
        '2. VORTEX BLOB (Gaussian):', ...
        '   ω(x,y,0) = Γ/(πσ²) · exp(-r²/σ²)', ...
        '   • Γ: Circulation strength', ...
        '   • σ: Core radius', ...
        '   • Radially symmetric vortex', ...
        '', ...
        '3. VORTEX PAIR:', ...
        '   Two counter-rotating vortices with specified separation', ...
        '   • Induces vortex merger dynamics', ...
        '   • Tests multi-vortex interaction', ...
        '', ...
        '4. MULTI-VORTEX:', ...
        '   Three or more vortices in configured positions', ...
        '   • Complex interaction patterns', ...
        '   • Chaotic vortex dynamics', ...
        '', ...
        '5. COUNTER-ROTATING PAIR:', ...
        '   Two vortices with opposite circulation', ...
        '   • Dipole propagation', ...
        '   • Self-advection dynamics', ...
        '═══════════════════════════════════════════════════════════════════════════════'};
end

function text = get_convergence_info_text()
    text = {
        '═══════════════════════════════════════════════════════════════════════════════', ...
        'CONVERGENCE STUDY METHODOLOGY:', ...
        '═══════════════════════════════════════════════════════════════════════════════', ...
        '', ...
        'RICHARDSON EXTRAPOLATION (Standard):', ...
        '  • Compares solutions at different grid resolutions', ...
        '  • Estimates discretization error: E ≈ A·h^p', ...
        '  • Extrapolates to h→0 for "exact" solution', ...
        '  • Reliable but requires multiple simulations', ...
        '', ...
        'ADAPTIVE PHYSICAL QUANTITY:', ...
        '  • Stage 1: Tests multiple physical quantities (max vorticity, energy, etc.)', ...
        '  • Stage 2: Identifies most sensitive quantity', ...
        '  • Stage 3: Uses selected quantity as convergence metric', ...
        '  • Minimizes computational cost', ...
        '', ...
        'AGENT-GUIDED REFINEMENT (Recommended):', ...
        '  • Predictive agent scores candidate meshes', ...
        '  • Scoring: S = w_e·E + w_c·C + w_v·V', ...
        '    - E: Error metric (lower is better)', ...
        '    - C: Computational cost (normalized)', ...
        '    - V: Vorticity stability', ...
        '  • Intelligent mesh selection minimizes total iterations', ...
        '  • Finds optimal mesh with 30-50% fewer simulations', ...
        '', ...
        'BINARY SEARCH WITH BRACKETING:', ...
        '  • Robust fallback method', ...
        '  • Guarantees convergence if bracket is valid', ...
        '  • Slower than agent-guided but very reliable', ...
        '', ...
        'CONVERGENCE TOLERANCE:', ...
        '  • 1% (0.01): Standard for most applications', ...
        '  • 0.1% (0.001): High precision (expensive)', ...
        '  • 5% (0.05): Exploratory (fast)', ...
        '═══════════════════════════════════════════════════════════════════════════════'};
end

function text = get_sustainability_info_text()
    text = {
        '═══════════════════════════════════════════════════════════════════════════════', ...
        'SUSTAINABILITY TRACKING FRAMEWORK (v4.1):', ...
        '═══════════════════════════════════════════════════════════════════════════════', ...
        '', ...
        'PURPOSE:', ...
        '  Track real-time energy consumption and computational sustainability', ...
        '  Build predictive energy scaling models: E = A · C^α', ...
        '  Quantify carbon footprint of numerical research', ...
        '', ...
        'ENERGY MONITORING:', ...
        '  • Hardware sensors track CPU power, temperature, frequency', ...
        '  • Python bridge communicates with OS-level monitors', ...
        '  • Sample intervals: 0.1-1.0 seconds (configurable)', ...
        '  • CSV logs stored in sensor_logs/ directory', ...
        '', ...
        'TRACKING MODES:', ...
        '  • Separate logs per mode: Isolate evolution vs. convergence costs', ...
        '  • Setup vs. Study: Capture hidden costs of convergence setup phases', ...
        '  • Most papers ignore setup costs - this framework captures full picture', ...
        '', ...
        'SUSTAINABILITY ANALYSIS:', ...
        '  • Build power-law models: E = A · C^α (α ≈ 1.5-2.0 for CFD)', ...
        '  • Predict energy costs for larger simulations', ...
        '  • Compare computational efficiency across methods', ...
        '  • Estimate carbon emissions (using grid energy mix)', ...
        '', ...
        'iCUE INTEGRATION (Optional):', ...
        '  • Corsair RGB lighting provides visual feedback', ...
        '  • Color-coded performance monitoring (green=efficient, red=high load)', ...
        '  • Requires Corsair iCUE SDK installation', ...
        '', ...
        'POST-SIMULATION REPORTING:', ...
        '  • EnergySustainabilityAnalyzer generates summary reports', ...
        '  • Scaling plots: Energy vs. computational cost', ...
        '  • Comparison tables: Method A vs. Method B efficiency', ...
        '  • Export to LaTeX for publication inclusion', ...
        '', ...
        'EXAMPLE WORKFLOW:', ...
        '  1. Enable monitoring in UI', ...
        '  2. Run convergence study (logs energy automatically)', ...
        '  3. Analyzer builds scaling model from logs', ...
        '  4. Predict energy cost for production N=1024 run', ...
        '  5. Include sustainability metrics in paper', ...
        '═══════════════════════════════════════════════════════════════════════════════'};
end

function update_mode_description(ui)
    % Update mode description when dropdown changes
    selected = ui.handles.mode_dropdown.Value;
    mode_map = containers.Map(...
        {'Evolution - Single Simulation', 'Convergence - Mesh Refinement Study', ...
         'Sweep - Parameter Sensitivity', 'Animation - High-FPS Visualization', ...
         'Experimentation - Multi-Configuration Test'}, ...
        {'evolution', 'convergence', 'sweep', 'animation', 'experimentation'});
    
    if isKey(mode_map, selected)
        mode = mode_map(selected);
        ui.handles.mode_description.Value = get_mode_description(mode);
    end
end

function update_ic_preview(ui)
    % Generate preview of selected IC
    try
        [X, Y] = meshgrid(linspace(0, 10, 100), linspace(0, 10, 100));
        
        ic_type_map = containers.Map(...
            {'Stretched Gaussian (Kutz)', 'Vortex Blob (Gaussian)', 'Vortex Pair', ...
             'Multi-Vortex', 'Counter-Rotating Pair', 'Custom'}, ...
            {'stretched_gaussian', 'vortex_blob_gaussian', 'vortex_pair', ...
             'multi_vortex', 'counter_rotating_pair', 'custom'});
        
        ic_type = ic_type_map(ui.handles.ic_dropdown.Value);
        c1 = ui.handles.ic_coeff1.Value;
        c2 = ui.handles.ic_coeff2.Value;
        
        switch ic_type
            case 'stretched_gaussian'
                omega = exp(-((c1*X).^2 + (c2*Y).^2));
            case 'vortex_blob_gaussian'
                r = sqrt((X-5).^2 + (Y-5).^2);
                omega = c1 * exp(-r.^2 / c2^2);
            case 'vortex_pair'
                r1 = sqrt((X-3).^2 + (Y-5).^2);
                r2 = sqrt((X-7).^2 + (Y-5).^2);
                omega = c1*exp(-r1.^2) - c1*exp(-r2.^2);
            case 'custom'
                % Evaluate custom code
                code = strjoin(ui.handles.custom_ic_code.Value, '\n');
                eval(code);
            otherwise
                omega = zeros(size(X));
        end
        
        contourf(ui.handles.ic_preview_axes, X, Y, omega, 20, 'LineStyle', 'none');
        colorbar(ui.handles.ic_preview_axes);
        title(ui.handles.ic_preview_axes, sprintf('IC Preview: %s', ic_type));
        xlabel(ui.handles.ic_preview_axes, 'X');
        ylabel(ui.handles.ic_preview_axes, 'Y');
    catch ME
        title(ui.handles.ic_preview_axes, ['Error: ' ME.message]);
    end
end

function save_custom_ic(ui)
    % Save custom IC as preset
    [file, path] = uiputfile('*.m', 'Save Custom IC Function');
    if file
        code = strjoin(ui.handles.custom_ic_code.Value, '\n');
        fid = fopen(fullfile(path, file), 'w');
        fprintf(fid, 'function omega = %s(X, Y)\n', strrep(file, '.m', ''));
        fprintf(fid, '%s\n', code);
        fprintf(fid, 'end\n');
        fclose(fid);
        uialert(ui.fig, 'Custom IC saved successfully!', 'Success');
    end
end

function validate_parameters(ui)
    % Validate numerical parameters and stability conditions
    Nx = ui.handles.Nx.Value;
    Ny = ui.handles.Ny.Value;
    Lx = ui.handles.Lx.Value;
    Ly = ui.handles.Ly.Value;
    dt = ui.handles.dt.Value;
    nu = ui.handles.nu.Value;
    
    dx = Lx / Nx;
    dy = Ly / Ny;
    
    % CFL condition
    u_max = 1.0;  % Assume max velocity
    CFL = u_max * dt / min(dx, dy);
    
    % Diffusion stability
    diff_stability = nu * dt / (min(dx, dy)^2);
    
    validation_text = {
        '═══════════════════════════════════════════════════════════════', ...
        'PARAMETER VALIDATION RESULTS:', ...
        '═══════════════════════════════════════════════════════════════', ...
        sprintf('Grid spacing: dx = %.4f m, dy = %.4f m', dx, dy), ...
        sprintf('Time step: dt = %.4f s', dt), ...
        sprintf('CFL number: %.4f (should be < 1.0)', CFL), ...
        sprintf('Diffusion number: %.6f (should be < 0.5)', diff_stability), ...
        ''};
    
    if CFL < 1.0
        validation_text{end+1} = '✓ CFL condition SATISFIED (stable)';
    else
        validation_text{end+1} = '✗ CFL condition VIOLATED (reduce dt or increase grid spacing)';
    end
    
    if diff_stability < 0.5
        validation_text{end+1} = '✓ Diffusion stability SATISFIED';
    else
        validation_text{end+1} = '✗ Diffusion instability (reduce dt or increase grid spacing)';
    end
    
    validation_text{end+1} = '';
    validation_text{end+1} = sprintf('Estimated memory usage: ~%.2f MB', Nx*Ny*8*10/1024/1024);
    validation_text{end+1} = sprintf('Estimated simulation time: ~%.1f minutes', Nx*Ny*dt*10/1e6);
    
    ui.handles.validation_display.Value = validation_text;
    ui.handles.cfl_indicator.Text = sprintf('CFL Number: %.4f', CFL);
    
    if CFL < 1.0 && diff_stability < 0.5
        ui.handles.cfl_indicator.FontColor = [0 0.7 0];
    else
        ui.handles.cfl_indicator.FontColor = [0.8 0 0];
    end
end

function load_preset(ui, preset_name)
    % Load predefined configuration preset
    switch preset_name
        case 'kutz'
            % Set method to Finite Difference
            ui.handles.method_group.SelectedObject = ui.handles.method_group.Buttons(1);
            ui.handles.mode_dropdown.Value = 'Evolution - Single Simulation';
            ui.handles.ic_dropdown.Value = 'Stretched Gaussian (Kutz)';
            ui.handles.ic_coeff1.Value = 2.0;
            ui.handles.ic_coeff2.Value = 0.2;
            ui.handles.Nx.Value = 128;
            ui.handles.Ny.Value = 128;
            ui.handles.Tfinal.Value = 8.0;
            
        case 'convergence'
            ui.handles.mode_dropdown.Value = 'Convergence - Mesh Refinement Study';
            ui.handles.conv_N_coarse.Value = 64;
            ui.handles.conv_N_max.Value = 512;
            ui.handles.conv_tol.Value = 0.01;
            ui.handles.conv_agent_enabled.Value = 1;
            
        case 'sweep_viscosity'
            ui.handles.mode_dropdown.Value = 'Sweep - Parameter Sensitivity';
            
        case 'animation'
            ui.handles.mode_dropdown.Value = 'Animation - High-FPS Visualization';
            ui.handles.anim_fps.Value = 60;
            ui.handles.create_animations.Value = 1;
    end
    
    update_mode_description(ui);
    uialert(ui.fig, sprintf('Loaded preset: %s', preset_name), 'Preset Loaded');
end

function export_configuration(ui)
    % Export current configuration to MAT file
    config = collect_ui_configuration(ui);
    
    [file, path] = uiputfile('*.mat', 'Export Configuration');
    if file
        save(fullfile(path, file), 'config');
        uialert(ui.fig, 'Configuration exported successfully!', 'Export Complete');
    end
end

function config = collect_ui_configuration(ui)
    % Collect all UI settings into configuration structure
    config = struct();
    
    % Method & Mode
    config.method = get_selected_method(ui);
    config.mode = get_selected_mode(ui);
    
    % Parameters (collect all numeric fields)
    fields = fieldnames(ui.handles);
    for i = 1:length(fields)
        field = fields{i};
        if isa(ui.handles.(field), 'matlab.ui.control.NumericEditField')
            config.(field) = ui.handles.(field).Value;
        elseif isa(ui.handles.(field), 'matlab.ui.control.CheckBox')
            config.(field) = ui.handles.(field).Value;
        elseif isa(ui.handles.(field), 'matlab.ui.control.DropDown')
            config.(field) = ui.handles.(field).Value;
        end
    end
end

function method = get_selected_method(ui)
    selected_btn = ui.handles.method_group.SelectedObject;
    if contains(selected_btn.Text, 'Finite Difference')
        method = 'Finite Difference';
    elseif contains(selected_btn.Text, 'Finite Volume')
        method = 'Finite Volume';
    else
        method = 'Spectral';
    end
end

function mode = get_selected_mode(ui)
    mode_str = ui.handles.mode_dropdown.Value;
    if contains(mode_str, 'Evolution')
        mode = 'evolution';
    elseif contains(mode_str, 'Convergence')
        mode = 'convergence';
    elseif contains(mode_str, 'Sweep')
        mode = 'sweep';
    elseif contains(mode_str, 'Animation')
        mode = 'animation';
    else
        mode = 'experimentation';
    end
end

function launch_simulation(ui)
    % Launch simulation with UI configuration
    config = collect_ui_configuration(ui);
    
    % Confirmation dialog
    answer = uiconfirm(ui.fig, ...
        sprintf('Launch %s simulation with %s method?', upper(config.mode), config.method), ...
        'Confirm Launch', ...
        'Icon', 'question');
    
    if strcmp(answer, 'OK')
        % Switch to monitor tabs
        ui.tab_group.SelectedTab = ui.tabs.exec_monitor;
        
        % Generate script to run Analysis.m with UI config
        % TODO: Integrate with Analysis.m
        
        uialert(ui.fig, ...
            'Simulation launch functionality will be integrated with Analysis.m', ...
            'Implementation Note');
    end
end
