function cfg = UI_Layout_Config()
% UI_LAYOUT_CONFIG - Centralized layout configuration for UIController
%
% Purpose:
%   Single source of truth for all UI layout parameters
%   Editing layout = edit this file only
%
% Returns:
%   cfg - struct with layout configuration
%
% Usage:
%   cfg = UI_Layout_Config();
%   main_grid = uigridlayout(parent, cfg.main_grid.rows_cols);
%   main_grid.ColumnWidth = cfg.main_grid.col_widths;
%
% Constraints:
%   - All sizes must be valid MATLAB layout specs
%   - Row/column indices must match component placement map
%
% References:
%   MATLAB uigridlayout documentation:
%   https://www.mathworks.com/help/matlab/ref/matlab.ui.container.gridlayout-properties.html

    % ===== ROOT FIGURE GRID =====
    % Top-level grid: toolbar (40px) | tab content (flexible) | hidden footer
    cfg.root_grid.rows_cols    = [3, 1];
    cfg.root_grid.row_heights  = {40, '1x', 0};       % Fixed toolbar, flexible content, hidden row
    cfg.root_grid.col_widths   = {'1x'};              % Single full-width column
    cfg.root_grid.padding      = [5 5 5 5];           % [top, bottom, left, right] in pixels
    cfg.root_grid.row_spacing  = 5;                   % Vertical spacing between rows
    cfg.root_grid.col_spacing  = 5;                   % Horizontal spacing (single column, minimal)

    % ===== TAB GROUP GRID =====
    % Tab group positioned in row 2 (flexible-height content area) of root grid
    cfg.tab_group.parent_row   = 2;                   % Row containing tabs
    cfg.tab_group.parent_col   = 1;                   % Column containing tabs
    cfg.tab_group.order        = {'config', 'monitoring', 'results'};  % Tab creation order

    % ===== STANDARD COMPONENT SIZES =====
    % Defines preferred heights for all UI element types (in pixels)
    cfg.sizes.button_height        = 34;              % Standard button height
    cfg.sizes.dropdown_height      = 30;              % Dropdown/combobox height
    cfg.sizes.edit_height          = 30;              % Single-line edit field
    cfg.sizes.label_height         = 22;              % Text label height
    cfg.sizes.checkbox_height      = 24;              % Checkbox control height
    cfg.sizes.textarea_height      = 78;              % Multi-line text area height
    cfg.sizes.panel_title_padding  = 10;              % Padding around panel titles
    cfg.sizes.form_row_height      = 30;              % Standard form row height
    cfg.sizes.form_row_tall        = 40;              % Tall form row (e.g., multi-line content)

    % ===== STANDARD HEIGHT ALIASES =====
    % Mirror sizes struct for easier reference in layout configs (cfg.heights.*)
    cfg.heights.button          = cfg.sizes.button_height;
    cfg.heights.dropdown        = cfg.sizes.dropdown_height;
    cfg.heights.edit            = cfg.sizes.edit_height;
    cfg.heights.label           = cfg.sizes.label_height;
    cfg.heights.checkbox        = cfg.sizes.checkbox_height;
    cfg.heights.textarea        = cfg.sizes.textarea_height;
    cfg.heights.form_row        = cfg.sizes.form_row_height;
    cfg.heights.form_row_tall   = cfg.sizes.form_row_tall;

    % ===== CONFIG TAB =====
    % Configuration tab: 2-column layout (left=1.1x wider, right=1x narrower)
    cfg.config_tab.root.rows_cols      = [1, 2];      % Single row, 2 columns
    cfg.config_tab.root.col_widths     = {'1.1x', '1x'};  % Left wider, right narrower
    cfg.config_tab.root.row_heights    = {'1x'};      % Single flexible row
    cfg.config_tab.root.padding        = [10 10 10 10]; % Inner padding all sides
    cfg.config_tab.root.row_spacing    = 10;          % Row spacing (not used: 1 row)
    cfg.config_tab.root.col_spacing    = 12;          % Column spacing between left/right

    % Left column: tabbed sections to reduce crowding.
    cfg.config_tab.left.rows_cols      = [1, 1];
    cfg.config_tab.left.row_heights    = {'1x'};
    cfg.config_tab.left.padding        = [8 8 8 8];
    cfg.config_tab.left.row_spacing    = 6;
    cfg.config_tab.left_subtabs = struct( ...
        'root', struct( ...
            'rows_cols', [1, 1], ...
            'row_heights', {'1x'}, ...
            'col_widths', {'1x'}, ...
            'padding', [0 0 0 0], ...
            'row_spacing', 0, ...
            'col_spacing', 0), ...
        'order', {{'method', 'grid', 'time', 'simulation', 'convergence', 'sustainability'}}, ...
        'titles', struct( ...
            'method', '[ ] Method and Mode', ...
            'grid', '[ ] Grid and Domain', ...
            'time', '[ ] Time and Physics', ...
            'simulation', '[ ] Simulation Settings', ...
            'convergence', '[ ] Convergence Study', ...
            'sustainability', '[ ] Sustainability'));

    % Right column: 3 stacked panels (readiness, initial condition, IC preview) with proportional heights
    cfg.config_tab.right.rows_cols     = [3, 1];      % 3 rows, 1 column
    cfg.config_tab.right.row_heights   = {'0.9x', '1.15x', '1.45x'};  % Proportional flexible sizing
    cfg.config_tab.right.padding       = [10 10 10 10]; % Panel internal padding
    cfg.config_tab.right.row_spacing   = 8;           % Vertical spacing between panels

    % Method panel: 5x4 grid for algorithm/mode selectors (5 control rows, 4 columns)
    cfg.config_tab.method_grid.rows_cols    = [5, 4]; % 5 rows, 4 columns
    cfg.config_tab.method_grid.col_widths   = {'1x', '1x', '1x', '1x'};  % Equal-width columns
    cfg.config_tab.method_grid.row_heights  = {cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.method_grid.padding      = [6 6 6 6]; % Inner padding
    cfg.config_tab.method_grid.row_spacing  = 6;       % Vertical spacing

    % Grid panel: 3x4 grid for domain/mesh parameters (Nx, Ny, Lx, Ly, etc.)
    cfg.config_tab.grid_grid.rows_cols     = [3, 4]; % 3 rows, 4 columns
    cfg.config_tab.grid_grid.col_widths    = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.grid_grid.row_heights   = {cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.grid_grid.padding       = [6 6 6 6];

    % Time panel: 2x4 grid for temporal parameters (dt, Tfinal, nu, etc.)
    cfg.config_tab.time_grid.rows_cols     = [2, 4]; % 2 rows, 4 columns
    cfg.config_tab.time_grid.col_widths    = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.time_grid.row_heights   = {cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.time_grid.padding       = [6 6 6 6];
    cfg.config_tab.time_video = struct( ...
        'panel_rows_cols', {[2, 1]}, ...
        'panel_row_heights', {{'1x', 'fit'}}, ...
        'preview_rows_cols', {[1, 3]}, ...
        'preview_col_widths', {{'1x', '1x', '1x'}}, ...
        'preview_padding', {[4 4 4 4]}, ...
        'preview_col_spacing', 6, ...
        'card_rows_cols', {[3, 1]}, ...
        'card_row_heights', {{'1x', 24, 24}}, ...
        'controls_rows_cols', {[1, 5]}, ...
        'controls_col_widths', {{'1x', '1x', '1x', '1x', '2x'}}, ...
        'controls_padding', {[0 0 0 0]}, ...
        'formats', {{'mp4', 'avi', 'gif'}}, ...
        'max_cached_frames', 180, ...
        'default_fps', 24);

    % Simulation panel: 3x4 grid for output/save/animation parameters
    cfg.config_tab.sim_grid.rows_cols      = [3, 4]; % 3 rows, 4 columns
    cfg.config_tab.sim_grid.col_widths     = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.sim_grid.row_heights    = {cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.sim_grid.padding        = [6 6 6 6];

    % Convergence panel: 5x4 grid for convergence study parameters (sweeps, ranges, etc.)
    cfg.config_tab.conv_grid.rows_cols     = [5, 4]; % 5 rows, 4 columns
    cfg.config_tab.conv_grid.col_widths    = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.conv_grid.row_heights   = {cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.conv_grid.padding       = [6 6 6 6];

    % Sustainability panel: 4x4 grid for monitoring/collector settings
    cfg.config_tab.sus_grid.rows_cols      = [4, 4]; % 4 rows, 4 columns
    cfg.config_tab.sus_grid.col_widths     = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.sus_grid.row_heights    = {cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};
    cfg.config_tab.sus_grid.padding        = [6 6 6 6];

    % Readiness panel: 3x1 column for pre-flight checks, status, and launch button
    cfg.config_tab.check_grid.rows_cols   = [3, 1]; % 3 rows, 1 column
    cfg.config_tab.check_grid.col_widths  = {'1x'};   % Full width
    cfg.config_tab.check_grid.row_heights = {64, 36, cfg.heights.button};  % Status, message, button
    cfg.config_tab.check_grid.padding     = [6 6 6 6];
    cfg.config_tab.check_grid.row_spacing = 4;       % Tight spacing

    % IC panel: 8x4 grid for initial condition parameters (type, amplitude, wavelength, etc.)
    cfg.config_tab.ic_grid.rows_cols     = [8, 4]; % 8 rows, 4 columns
    cfg.config_tab.ic_grid.col_widths    = {'1x', '1x', '1x', '1x'};
    cfg.config_tab.ic_grid.row_heights   = {cfg.heights.form_row, cfg.heights.form_row, 92, 72, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row, cfg.heights.form_row};  % Fixed + spacious rows
    cfg.config_tab.ic_grid.padding       = [6 6 6 6];
    cfg.config_tab.ic_grid.row_spacing   = 6;

    % ===== MONITOR TAB =====
    % Live monitoring: 2-column layout (main plots 3x wider, sidebar 1x narrower)
    cfg.monitor_tab.root.rows_cols     = [1, 2];      % Single row, 2 columns
    cfg.monitor_tab.root.col_widths    = {'3x', '1x'};  % Left: plots (wider), Right: sidebar
    cfg.monitor_tab.root.row_heights   = {'1x'};      % Single flexible row
    cfg.monitor_tab.root.padding       = [10 10 10 10]; % Inner padding
    cfg.monitor_tab.root.col_spacing   = 12;          % Column spacing

    % 3x3 plot grid configuration (8 plots + 1 numeric metrics panel)
    cfg.monitor_tab.plot_grid_rows      = 3;          % 3 rows in plot grid
    cfg.monitor_tab.plot_grid_cols      = 3;          % 3 columns in plot grid
    cfg.monitor_tab.plot_tile_count     = 9;          % Total tiles (3x3)
    cfg.monitor_tab.numeric_tile_index  = 9;          % Last tile (position 9) is numeric display
    cfg.monitor_tab.plot_area_ratio     = 0.75;       % Plots occupy 75% of available space

    % Plot grid: 3x3 equal tiles with flexible sizing
    cfg.monitor_tab.left.rows_cols   = [cfg.monitor_tab.plot_grid_rows, cfg.monitor_tab.plot_grid_cols];  % 3x3
    cfg.monitor_tab.left.row_heights = {'1x', '1x', '1x'};  % Equal-height rows
    cfg.monitor_tab.left.col_widths  = {'1x', '1x', '1x'};  % Equal-width columns
    cfg.monitor_tab.left.padding     = [8 8 8 8];   % Inner padding per tile
    cfg.monitor_tab.left.row_spacing = 10;          % Vertical spacing between tiles
    cfg.monitor_tab.left.col_spacing = 10;          % Horizontal spacing between tiles

    % Sidebar: 4x1 column for terminal, status, metrics, and run info
    cfg.monitor_tab.sidebar.rows_cols      = [4, 1]; % 4 rows, 1 column
    cfg.monitor_tab.sidebar.row_heights    = {36, 24, '1x', 'fit'};  % Fixed + flexible + auto-fit
    cfg.monitor_tab.sidebar.padding        = [8 8 8 8]; % Inner padding
    cfg.monitor_tab.sidebar.row_spacing    = 8;       % Vertical spacing
    cfg.monitor_tab.live_update = struct( ...
        'refresh_stride', 2, ...           % Refresh plots every N accepted payloads
        'min_refresh_seconds', 0.12, ...   % Time-based refresh floor
        'force_refresh_every', 25, ...     % Guaranteed refresh cadence
        'max_history_points', 500);        % Keep tail samples for responsive plotting
    all_methods = {'finite_difference', 'finite_volume', 'spectral'};
    all_modes = {'evolution', 'convergence', 'sweep', 'animation', 'experimentation'};
    conv_only = {'convergence'};
    cfg.monitor_tab.metric_catalog = struct( ...
        'id', {'iter_vs_time', 'iter_per_sec', 'runtime_vs_time', 'max_vorticity', ...
               'energy_proxy', 'enstrophy_proxy', 'vorticity_decay_rate', 'cpu_proxy', ...
               'memory_mb', 'iteration_completion', 'stability_proxy', 'convergence_residual'}, ...
        'title', {'Iterations', 'Iterations/s', 'Runtime', 'Max $|\omega|$', ...
                  'Energy Proxy', 'Enstrophy Proxy', 'Decay Rate', 'CPU Usage', ...
                  'Memory Usage', 'Completion', 'Stability Proxy', 'Convergence Residual'}, ...
        'xlabel', {'Physical time', 'Physical time', 'Physical time', 'Physical time', ...
                   'Physical time', 'Physical time', 'Physical time', 'Physical time', ...
                   'Physical time', 'Physical time', 'Physical time', 'Iteration'}, ...
        'ylabel', {'iters', 'iters/s', 's', '$|\omega|_{max}$', ...
                   '$E^*$', '$Z^*$', '$-d|\omega|/dt$', 'CPU (%)', ...
                   'MB', '%', 'proxy', 'residual'}, ...
        'methods', {all_methods, all_methods, all_methods, all_methods, ...
                    all_methods, all_methods, all_methods, all_methods, ...
                    all_methods, all_methods, all_methods, all_methods}, ...
        'modes', {all_modes, all_modes, all_modes, all_modes, ...
                  all_modes, all_modes, all_modes, all_modes, ...
                  all_modes, all_modes, all_modes, conv_only}, ...
        'rank', num2cell([1, 2, 5, 3, 4, 6, 8, 9, 10, 11, 12, 7]));

    % ===== RESULTS TAB =====
    % Results display: 2-row layout (figures flexible + metrics fixed 140px)
    cfg.results_tab.root.rows_cols     = [2, 1];      % 2 rows, 1 column
    cfg.results_tab.root.row_heights   = {'1x', 140}; % Figures flexible, metrics fixed
    cfg.results_tab.root.padding       = [10 10 10 10]; % Inner padding
    cfg.results_tab.root.row_spacing   = 10;          % Vertical spacing

    % Figure display grid: controls + figure canvas
    cfg.results_tab.fig_grid.rows_cols    = [2, 1]; % 2 rows, 1 column
    cfg.results_tab.fig_grid.row_heights  = {cfg.heights.form_row_tall, '1x'};  % Control bar + canvas
    cfg.results_tab.fig_grid.padding      = [6 6 6 6];

    % Control bar: 1x5 grid for navigation and action buttons
    cfg.results_tab.controls.rows_cols  = [1, 5]; % 1 row, 5 columns
    cfg.results_tab.controls.col_widths = {90, '1x', 110, 100, 90};  % Mixed fixed/flexible
    cfg.results_tab.controls.row_heights = {cfg.heights.button};
    cfg.results_tab.controls.padding    = [0 0 0 0]; % No padding (tight)
    cfg.results_tab.controls.col_spacing = 8;      % Column spacing

    % ===== EXPLICIT GRID COORDINATES =====
    % Maps component names to grid positions [row, col, rowspan, colspan]
    % Used for programmatic placement and to avoid magic numbers in controller code
    cfg.coords = struct();

    % Configuration tab coordinates
    cfg.coords.config.left              = [1, 1, 1, 1];  % Left column (entire column)
    cfg.coords.config.right             = [1, 2, 1, 1];  % Right column (entire column)
    cfg.coords.config.panel_method      = [1, 1, 1, 1];  % Method panel (left row 1)
    cfg.coords.config.panel_grid        = [2, 1, 1, 1];  % Grid panel (left row 2)
    cfg.coords.config.panel_time        = [3, 1, 1, 1];  % Time panel (left row 3)
    cfg.coords.config.panel_sim         = [4, 1, 1, 1];  % Sim panel (left row 4)
    cfg.coords.config.panel_conv        = [5, 1, 1, 1];  % Convergence panel (left row 5)
    cfg.coords.config.panel_sus         = [6, 1, 1, 1];  % Sustainability panel (left row 6)
    cfg.coords.config.panel_check       = [1, 1, 1, 1];  % Readiness panel (right row 1)
    cfg.coords.config.panel_ic          = [2, 1, 1, 1];  % IC panel (right row 2)
    cfg.coords.config.panel_preview     = [3, 1, 1, 1];  % IC Preview panel (right row 3)

    % Monitor tab coordinates
    cfg.coords.monitor.left_panel        = [1, 1, 1, 1];  % Plot grid (row 1, col 1)
    cfg.coords.monitor.terminal_panel   = [1, 2, 1, 1];  % Sidebar (row 1, col 2)
    cfg.coords.monitor.panel_iter_time  = [1, 1, 1, 1];  % Iteration time plot (grid pos)
    cfg.coords.monitor.panel_iter_per_sec = [1, 2, 1, 1]; % Iterations/sec plot (grid pos)
    cfg.coords.monitor.panel_conv       = [2, 1, 1, 1];  % Convergence plot (grid pos)
    cfg.coords.monitor.panel_metrics    = [2, 2, 1, 1];  % Metrics panel (grid pos)

    % Results tab coordinates
    cfg.coords.results.panel_fig      = [1, 1, 1, 1];  % Figure display (row 1)
    cfg.coords.results.panel_metrics  = [2, 1, 1, 1];  % Metrics summary (row 2)

    % ===== UI TEXT MANIFEST =====
    % Centralized human-facing strings used by major layout panels/tabs.
    % Enables easy internationalization and consistent UI labeling
    cfg.text.app_title = 'Tsunami Vortex Simulation UI';  % Main window title
    cfg.text.tabs = struct( ...
        'config', 'Configuration', ...
        'monitoring', 'Live Monitor', ...
        'results', 'Results and Figures');
    cfg.text.config_panels = struct( ...
        'method', 'Method and Mode', ...
        'grid', 'Grid and Domain', ...
        'time', 'Time and Physics', ...
        'simulation', 'Simulation Settings', ...
        'convergence', 'Convergence Study', ...
        'sustainability', 'Sustainability', ...
        'readiness', 'Readiness Checklist', ...
        'ic', 'Initial Condition', ...
        'preview', 'IC Preview (t=0)');
    cfg.text.monitor_panels = struct( ...
        'dashboard', 'Live Monitor Dashboard (3x3: 8 plots + 1 numeric tile)', ...
        'numeric_tile', 'Simulation Metrics (Categorized)', ...
        'sidebar', 'Terminal and Telemetry', ...
        'collector', 'Collector Probe and Runtime Signals');
    cfg.text.results_panels = struct( ...
        'figures', 'Figures', ...
        'metrics', 'Metrics Summary');
    cfg.text.placeholder = struct( ...
        'value', '<placeholder>', ...
        'description_prefix', 'Placeholder for');

    % ===== EDITOR-FACING UI STRING MANIFEST =====
    % Every user-visible UI string should be routed through this block.
    % Keep this section as the first stop when renaming tabs/labels/buttons.
    cfg.ui_text = struct();

    cfg.ui_text.window = struct( ...
        'main_title', 'Tsunami Numerical Simulation UI', ...
        'menu_title', 'Tsunami Vortex Simulation UI');

    cfg.ui_text.startup = struct( ...
        'dialog_title', 'Simulation Mode Selection', ...
        'header', 'Choose Simulation Interface', ...
        'description', 'How would you like to run the simulation?', ...
        'ui_mode_button', sprintf('UI Mode\n(Full Configuration Interface)'), ...
        'traditional_mode_button', sprintf('Traditional\n(Separate Windows)'));

    cfg.ui_text.menu = struct( ...
        'dev_mode_off', 'Developer Mode: OFF', ...
        'dev_mode_on', 'Developer Mode: ON', ...
        'dev_enabled_log', 'Developer Mode ENABLED. Click any component to inspect.', ...
        'dev_disabled_log', 'Developer Mode DISABLED.');

    cfg.ui_text.config = struct();
    cfg.ui_text.config.root = struct( ...
        'left_panel_title', 'Configuration', ...
        'right_panel_title', 'Initial Conditions and Preview');

    cfg.ui_text.config.method = struct( ...
        'panel_title', 'Method and Mode', ...
        'method_label', 'Method', ...
        'mode_label', 'Mode', ...
        'boundary_label', 'Boundary', ...
        'boundary_periodic', 'Periodic (x,y)', ...
        'boundary_with_bathy', 'Periodic (x,y) + Bathymetry', ...
        'boundary_with_motion', 'Periodic (x,y) + Motion', ...
        'boundary_with_bathy_motion', 'Periodic (x,y) + Bathymetry + Motion', ...
        'bathy_checkbox', 'Use Bathymetry', ...
        'bathy_placeholder', 'Bathymetry file', ...
        'bathy_browse_button', 'Browse', ...
        'motion_checkbox', 'Enable Seabed Motion', ...
        'motion_amplitude_label', 'Amplitude', ...
        'physics_status_ready', 'Bathymetry and motion configured independently', ...
        'physics_status_non_fd', 'Bathymetry/motion disabled for non-FD method');

    cfg.ui_text.config.grid = struct( ...
        'panel_title', 'Grid and Domain', ...
        'delta_label', 'Delta', ...
        'grid_points_label', 'Grid points');

    cfg.ui_text.config.time = struct( ...
        'panel_title', 'Time and Physics', ...
        'snapshots_label', 'Snapshots', ...
        'video_panel_title', 'Build Time/Physics Animation Preview (MP4 | AVI | GIF)', ...
        'video_status_pending_pattern', '%s: pending', ...
        'video_status_missing_pattern', '%s: missing', ...
        'video_status_load_failed_pattern', '%s: load failed', ...
        'video_status_loaded_pattern', '%s: loaded %d frame(s)', ...
        'video_status_empty_stream_pattern', '%s: empty stream', ...
        'video_codec_placeholder', 'Codec: --', ...
        'video_codec_file_missing', 'Codec: file not found', ...
        'video_codec_no_frames', 'Codec: no frames decoded', ...
        'video_codec_videoreader_pattern', 'Codec: VideoReader @ %.1f fps', ...
        'video_codec_gif_pattern', 'Codec: GIF @ %.1f fps', ...
        'video_codec_error_pattern', 'Codec: %s', ...
        'video_play_button', 'Play', ...
        'video_pause_button', 'Pause', ...
        'video_restart_button', 'Restart', ...
        'video_load_button', 'Load Latest', ...
        'video_status_idle', 'Triplet status: idle');

    cfg.ui_text.config.simulation = struct( ...
        'panel_title', 'Simulation Settings', ...
        'save_csv_checkbox', 'Save CSV', ...
        'save_mat_checkbox', 'Save MAT', ...
        'save_png_checkbox', 'Save PNG', ...
        'save_fig_checkbox', 'Save FIG', ...
        'dpi_label', 'DPI', ...
        'close_after_save_checkbox', 'Close after save', ...
        'use_owl_saver_checkbox', 'Use OWL saver', ...
        'create_animations_checkbox', 'Create animations');

    cfg.ui_text.config.convergence = struct( ...
        'panel_title', 'Convergence Study', ...
        'n_coarse_label', 'N coarse', ...
        'n_max_label', 'N max', ...
        'tolerance_label', 'Tolerance', ...
        'criterion_label', 'Criterion', ...
        'max_jumps_label', 'Max jumps', ...
        'binary_checkbox', 'Binary search', ...
        'adaptive_checkbox', 'Adaptive', ...
        'agent_guided_checkbox', 'Agent-guided', ...
        'load_mesh_button', 'Load converged mesh preset', ...
        'no_mesh_loaded', 'No preset loaded', ...
        'agent_status_inactive', 'Convergence mode inactive', ...
        'agent_status_locked', 'Agent mode: manual fields locked', ...
        'agent_status_manual', 'Manual mode: controls editable');

    cfg.ui_text.config.sustainability = struct( ...
        'panel_title', 'Sustainability', ...
        'enable_monitoring_checkbox', 'Enable monitoring', ...
        'sample_interval_label', 'Sample interval (s)', ...
        'always_log_checkbox', 'Always log run ledger', ...
        'cpuz_checkbox', 'CPU-Z collector', ...
        'hwinfo_checkbox', 'HWiNFO collector', ...
        'icue_checkbox', 'iCUE collector', ...
        'strict_checkbox', 'Strict external checks', ...
        'machine_tag_label', 'Machine tag', ...
        'collector_status_template', 'Collector readiness: %d/%d external connected', ...
        'collector_status_strict', 'Collector readiness: strict mode requires at least one external collector');

    cfg.ui_text.config.readiness = struct( ...
        'panel_title', 'Readiness Checklist', ...
        'checks', {{'Grid', 'Domain', 'Time', 'IC', 'Convergence', 'Monitor', 'Collectors', 'Outputs'}}, ...
        'check_state_unchecked', '[ ]', ...
        'defaults_summary_template', 'Defaults source: create_default_parameters.m -> %s + %s', ...
        'legend_template', 'Legend: green = ready, red = needs input\n%s', ...
        'launch_button', 'Launch', ...
        'export_button', 'Export', ...
        'import_button', 'Import');

    cfg.ui_text.config.initial_condition = struct( ...
        'panel_title', 'Initial Condition', ...
        'ic_type_label', 'IC Type', ...
        'pattern_label', 'Pattern', ...
        'scale_label', 'Scale Factor', ...
        'count_label', 'Count (N)', ...
        'where_lines', {{'where:', 'a,b > 0 control spread in x/y', 'x0,y0 set center position'}}, ...
        'coeff1_label', 'Coeff 1', ...
        'coeff2_label', 'Coeff 2', ...
        'coeff3_label', 'Coeff 3', ...
        'coeff4_label', 'Coeff 4', ...
        'center_x_label', 'Center x0', ...
        'center_y_label', 'Center y0', ...
        'status_ready', 'IC ready');

    cfg.ui_text.config.preview = struct( ...
        'panel_title', 'IC Preview (t=0)');

    cfg.ui_text.monitor = struct();
    cfg.ui_text.monitor.sidebar = struct( ...
        'panel_title', 'Terminal and Telemetry', ...
        'save_log_button', 'Save Log', ...
        'clear_button', 'Clear', ...
        'run_status_idle', 'Idle', ...
        'collector_panel_title', 'Collector Probe and Runtime Signals', ...
        'collector_probe_waiting', 'Probe status: waiting for first scan', ...
        'collector_probe_template', 'Probe @ %s: %d/%d external connected', ...
        'collector_headers', {{'MATLAB', 'CPU-Z', 'HWiNFO', 'iCUE'}}, ...
        'collector_state_ready', 'ready', ...
        'collector_state_off', 'off', ...
        'collector_state_connected', 'connected', ...
        'collector_state_missing', 'not found', ...
        'retry_all_button', 'Probe All', ...
        'retry_cpuz_button', 'Retry CPU-Z', ...
        'retry_hwinfo_button', 'Retry HWiNFO', ...
        'retry_icue_button', 'Retry iCUE');

    cfg.ui_text.monitor.numeric_tile = struct( ...
        'column_name', 'Metric Summary', ...
        'placeholder_rows', {{ ...
            '[Session] Status: Waiting for run', ...
            '[Iteration] Runtime: -- s', ...
            '[Iteration] Iteration: -- iter', ...
            '[Iteration] Iterations/s: -- iter/s', ...
            '[Solution] Max |omega|: --', ...
            '[Convergence] Tolerance: --', ...
            '[Convergence] Metric: --', ...
            '[Convergence] Suggested coarse N: --', ...
            '[Computer] CPU usage: -- %', ...
            '[Computer] Memory: -- MB', ...
            '[System] Machine: --', ...
            '[System] Collectors: --'}}, ...
        'categories', struct( ...
            'session', 'Session', ...
            'iteration', 'Iteration', ...
            'solution', 'Solution', ...
            'computer', 'Computer', ...
            'convergence', 'Convergence', ...
            'grid', 'Grid', ...
            'system', 'System'), ...
        'labels', struct( ...
            'status', 'Status', ...
            'runtime', 'Runtime', ...
            'iteration', 'Iteration', ...
            'iterations_per_sec', 'Iterations/s', ...
            'max_omega', 'Max |omega|', ...
            'cpu_usage', 'CPU usage', ...
            'memory', 'Memory', ...
            'tolerance', 'Tolerance', ...
            'metric', 'Metric', ...
            'suggested_coarse_n', 'Suggested coarse N', ...
            'mesh', 'Mesh', ...
            'dt', 'dt', ...
            'tfinal', 'Tfinal', ...
            'domain_lx', 'Domain Lx', ...
            'domain_ly', 'Domain Ly', ...
            'mode', 'Mode', ...
            'method', 'Method', ...
            'monitor_profile', 'Monitor profile', ...
            'run_id', 'Run ID', ...
            'machine', 'Machine', ...
            'collectors', 'Collectors'));
    cfg.ui_text.monitor.runtime = struct( ...
        'running_mode_pattern', 'Running %s...', ...
        'running_iteration_pattern', 'Running iteration %d', ...
        'running_progress_pattern', 'Running %d/%d (%.1f%%%%)', ...
        'status_ready', 'Ready', ...
        'status_running', 'Running', ...
        'status_completed', 'Completed', ...
        'source_ui', 'UI', ...
        'source_runtime', 'Runtime', ...
        'source_dispatcher', 'Dispatcher');

    cfg.ui_text.results = struct( ...
        'figure_label', 'Figure', ...
        'figure_none', 'No figures yet', ...
        'save_current_button', 'Save Current', ...
        'export_all_button', 'Export All', ...
        'refresh_button', 'Refresh', ...
        'preview_tab_title', 'Preview', ...
        'preview_axes_title', 'Figures will appear here during simulation', ...
        'metrics_panel_title', 'Metrics and History', ...
        'metrics_placeholder', 'Run a simulation to populate metrics and history.');

    cfg.ui_text.terminal = struct( ...
        'cleared', 'Terminal cleared', ...
        'waiting_html', "<span style='color:#8ab4f8;'>[terminal]</span> waiting for output...");

    cfg.ui_text.alerts = struct( ...
        'empty_log_body', 'No terminal output to save', ...
        'empty_log_title', 'Empty Log', ...
        'save_terminal_log_dialog_title', 'Save Terminal Log', ...
        'no_figures_body', 'No figures to save', ...
        'no_figures_title', 'No Figures', ...
        'no_figures_export_body', 'No figures to export', ...
        'save_figure_dialog_title', 'Save Figure As', ...
        'export_directory_dialog_title', 'Select Export Directory for All Figures');

    cfg.ui_text.developer = struct( ...
        'inspector_window_title', 'UI Developer Inspector', ...
        'inspector_title', 'Component Inspector', ...
        'inspector_instructions', 'Click any UI component to inspect', ...
        'selected_component_panel', 'Selected Component', ...
        'layout_tools_panel', 'Layout Tools', ...
        'inspector_log_panel', 'Inspector Log', ...
        'validate_button', 'Validate All Layouts', ...
        'dump_button', 'Dump UI Map to Console', ...
        'reset_button', 'Reset to Default Layout', ...
        'type_label', 'Type:', ...
        'parent_label', 'Parent:', ...
        'layout_row_label', 'Layout.Row:', ...
        'layout_col_label', 'Layout.Column:', ...
        'row_span_label', 'Row Span:', ...
        'col_span_label', 'Col Span:', ...
        'parent_rows_label', 'Parent Grid Rows:', ...
        'parent_cols_label', 'Parent Grid Cols:', ...
        'callbacks_label', 'Callbacks:', ...
        'tag_label', 'Tag/ID:', ...
        'none_value', '(none)', ...
        'log_initial', 'Developer Mode Active');

    cfg.ui_text.monitor_metric_na = struct( ...
        'msg_1', 'Metric not applicable', ...
        'title_suffix', ' (N/A)');

    % ===== EDITOR-FACING UI OPTIONS =====
    % Dropdown/menu item lists used by create_* methods.
    cfg.ui_options = struct();
    cfg.ui_options.method_items = {'Finite Difference', 'Finite Volume', 'Spectral'};
    cfg.ui_options.mode_items = {'Evolution', 'Convergence', 'Sweep', 'Animation', 'Experimentation'};
    cfg.ui_options.motion_model_items = {'none', 'sinusoidal', 'gaussian_pulse', 'file_driven'};
    cfg.ui_options.animation_format_items = {'mp4', 'avi', 'gif'};
    cfg.ui_options.convergence_criterion_items = {'l2_relative', 'l2_absolute', 'linf_relative', 'max_vorticity', 'energy_dissipation', 'auto_physical'};
    cfg.ui_options.ic_type_items = {'Stretched Gaussian', 'Vortex Blob', 'Vortex Pair', 'Multi-Vortex', ...
        'Lamb-Oseen', 'Rankine', 'Lamb Dipole', 'Taylor-Green', 'Random Turbulence', 'Elliptical Vortex'};
    cfg.ui_options.ic_pattern_items = {'single', 'circular', 'grid', 'random'};

    % ===== EDITOR-FACING UI DEFAULTS =====
    % Default control values and placeholders for first render.
    cfg.ui_defaults = struct();
    cfg.ui_defaults.method = 'Finite Difference';
    cfg.ui_defaults.mode = 'Evolution';
    cfg.ui_defaults.boundary_label = cfg.ui_text.config.method.boundary_periodic;
    cfg.ui_defaults.bathymetry_enabled = false;
    cfg.ui_defaults.bathymetry_file = '';
    cfg.ui_defaults.motion_enabled = false;
    cfg.ui_defaults.motion_model = 'none';
    cfg.ui_defaults.motion_amplitude = 0.0;

    cfg.ui_defaults.Nx = 128;
    cfg.ui_defaults.Ny = 128;
    cfg.ui_defaults.Lx = 10.0;
    cfg.ui_defaults.Ly = 10.0;
    cfg.ui_defaults.delta = 2;
    cfg.ui_defaults.grid_points = '16384';

    cfg.ui_defaults.dt = 0.001;
    cfg.ui_defaults.t_final = 10.0;
    cfg.ui_defaults.nu = 1e-4;
    cfg.ui_defaults.num_snapshots = 9;

    cfg.ui_defaults.save_csv = true;
    cfg.ui_defaults.save_mat = true;
    cfg.ui_defaults.figures_save_png = true;
    cfg.ui_defaults.figures_save_fig = false;
    cfg.ui_defaults.figures_dpi = 300;
    cfg.ui_defaults.figures_close_after_save = false;
    cfg.ui_defaults.figures_use_owl_saver = true;
    cfg.ui_defaults.create_animations = true;
    cfg.ui_defaults.animation_format = 'mp4';
    cfg.ui_defaults.animation_fps = 30;
    cfg.ui_defaults.animation_num_frames = 100;

    cfg.ui_defaults.convergence_N_coarse = 64;
    cfg.ui_defaults.convergence_N_max = 512;
    cfg.ui_defaults.convergence_tol = 1e-2;
    cfg.ui_defaults.convergence_criterion_type = 'l2_relative';
    cfg.ui_defaults.convergence_binary = true;
    cfg.ui_defaults.convergence_use_adaptive = true;
    cfg.ui_defaults.convergence_max_jumps = 5;
    cfg.ui_defaults.convergence_agent_enabled = true;

    cfg.ui_defaults.enable_monitoring = true;
    cfg.ui_defaults.sample_interval = 0.5;
    cfg.ui_defaults.sustainability_auto_log = true;
    cfg.ui_defaults.collector_cpuz = false;
    cfg.ui_defaults.collector_hwinfo = false;
    cfg.ui_defaults.collector_icue = false;
    cfg.ui_defaults.collector_strict = false;
    cfg.ui_defaults.machine_tag = getenv('COMPUTERNAME');

    cfg.ui_defaults.ic_type = 'Stretched Gaussian';
    cfg.ui_defaults.ic_pattern = 'single';
    cfg.ui_defaults.ic_scale = 1.0;
    cfg.ui_defaults.ic_count = 1;
    cfg.ui_defaults.ic_coeff1 = 2.0;
    cfg.ui_defaults.ic_coeff2 = 0.2;
    cfg.ui_defaults.ic_coeff3 = 0.0;
    cfg.ui_defaults.ic_coeff4 = 0.0;
    cfg.ui_defaults.ic_center_x = 0.0;
    cfg.ui_defaults.ic_center_y = 0.0;

    % ===== DEFAULTS PROVENANCE =====
    % Clarifies where launch defaults are loaded from.
    % Helpful for debugging and understanding configuration flow
    cfg.defaults_source = struct( ...
        'summary', 'Startup defaults are loaded via create_default_parameters.m and mirrored in Scripts/Editable/Parameters.m + Scripts/Editable/Settings.m', ...
        'loader', 'Scripts/Infrastructure/Initialisers/create_default_parameters.m', ...
        'editable_parameters', 'Scripts/Editable/Parameters.m', ...
        'editable_settings', 'Scripts/Editable/Settings.m', ...
        'default_keys', {{'method', 'mode', 'Nx', 'Ny', 'Lx', 'Ly', 'dt', 'Tfinal', 'nu', ...
            'num_snapshots', 'ic_type', 'create_animations', 'animation_format', ...
            'animation_fps', 'bathymetry_enabled'}});

    % ===== MATH TEXT TOKENS =====
    % Canonical LaTeX label strings used across dialogs and math-facing labels.
    cfg.math_tokens = struct( ...
        'N_x', '$N_x$', ...
        'N_y', '$N_y$', ...
        'L_x', '$L_x$', ...
        'L_y', '$L_y$', ...
        'Delta_t', '$\Delta t$', ...
        'T_final', '$T_{final}$', ...
        'nu', '$\nu$', ...
        'epsilon', '$\epsilon$', ...
        'omega', '$\omega$');

    % ===== LAYOUT MANIFEST =====
    % This manifest is consumed by UI_Layout_Sandbox for rapid UI trialing.
    % Provides a flat map of major UI components for debugging and visualization
    cfg.layout_manifest = build_layout_manifest(cfg);
    cfg.tab_layout = build_tab_layout_groups(cfg);

    % ===== DEVELOPER MODE SETTINGS =====
    % Enable inspector overlay and component highlighting for layout debugging
    cfg.dev_mode.enabled         = false;  % Default off - set true to enable inspector
    cfg.dev_mode.inspector_width = 300;    % pixels - width of inspector panel
    cfg.dev_mode.highlight_color = [1 0.8 0];  % yellow - RGB color for highlighting
    cfg.dev_mode.highlight_width = 2;      % pixels - outline thickness
    
    % ===== COLOR SCHEME (Dark Mode) =====
    % RGB color values (0-1 scale) for consistent dark-mode styling
    % Background colors (dark -> light)
    cfg.colors.bg_dark        = [0.11 0.11 0.11];  % Darkest background
    cfg.colors.bg_panel       = [0.16 0.16 0.16];  % Standard panel background
    cfg.colors.bg_panel_alt   = [0.20 0.20 0.20];  % Alternate panel (contrast)
    cfg.colors.bg_input       = [0.13 0.13 0.13];  % Input field background
    % Text colors
    cfg.colors.fg_text        = [0.90 0.90 0.90];  % Primary text (bright white)
    cfg.colors.fg_muted       = [0.72 0.72 0.72];  % Secondary text (dimmed)
    % Accent colors (status/semantic)
    cfg.colors.accent_green   = [0.25 0.78 0.35];  % Success/valid status
    cfg.colors.accent_yellow  = [0.95 0.72 0.20];  % Warning/caution status
    cfg.colors.accent_red     = [0.90 0.35 0.35];  % Error/invalid status
    cfg.colors.accent_cyan    = [0.35 0.72 0.95];  % Info/highlight status
    cfg.colors.accent_gray    = [0.60 0.60 0.60];  % Disabled/inactive state
    
end

function tab_layout = build_tab_layout_groups(cfg)
    % build_tab_layout_groups - Group layout controls per tab for easier editing.
    %
    % Field order inside each tab group:
    %   tab_name -> grid -> sections -> sub_tabs -> plots
    %
    % This is an editor-facing organization layer and keeps legacy fields intact
    % (`cfg.config_tab`, `cfg.monitor_tab`, `cfg.results_tab`) for compatibility.

    tab_layout = struct();

    tab_layout.config = struct( ...
        'tab_name', cfg.text.tabs.config, ...
        'grid', cfg.config_tab.root, ...
        'sections', struct( ...
            'left_column', cfg.config_tab.left, ...
            'left_subtabs', cfg.config_tab.left_subtabs, ...
            'right_column', cfg.config_tab.right, ...
            'method', cfg.config_tab.method_grid, ...
            'grid', cfg.config_tab.grid_grid, ...
            'time', cfg.config_tab.time_grid, ...
            'time_video', cfg.config_tab.time_video, ...
            'simulation', cfg.config_tab.sim_grid, ...
            'convergence', cfg.config_tab.conv_grid, ...
            'sustainability', cfg.config_tab.sus_grid, ...
            'readiness', cfg.config_tab.check_grid, ...
            'initial_condition', cfg.config_tab.ic_grid), ...
        'sub_tabs', cfg.config_tab.left_subtabs.titles, ...
        'plots', struct(), ...
        'coords', cfg.coords.config);

    tab_layout.monitoring = struct( ...
        'tab_name', cfg.text.tabs.monitoring, ...
        'grid', cfg.monitor_tab.root, ...
        'sections', struct( ...
            'dashboard_grid', cfg.monitor_tab.left, ...
            'sidebar', cfg.monitor_tab.sidebar), ...
        'sub_tabs', struct(), ...
        'plots', struct( ...
            'plot_grid_rows', cfg.monitor_tab.plot_grid_rows, ...
            'plot_grid_cols', cfg.monitor_tab.plot_grid_cols, ...
            'plot_tile_count', cfg.monitor_tab.plot_tile_count, ...
            'numeric_tile_index', cfg.monitor_tab.numeric_tile_index, ...
            'live_update', cfg.monitor_tab.live_update), ...
        'coords', cfg.coords.monitor);

    tab_layout.results = struct( ...
        'tab_name', cfg.text.tabs.results, ...
        'grid', cfg.results_tab.root, ...
        'sections', struct( ...
            'figure_area', cfg.results_tab.fig_grid, ...
            'control_row', cfg.results_tab.controls), ...
        'sub_tabs', struct('default_preview', 'Preview'), ...
        'plots', struct(), ...
        'coords', cfg.coords.results);
end

function manifest = build_layout_manifest(cfg)
    % build_layout_manifest - Flat major-component map for sandbox rendering.
    % Creates a comprehensive index of all UI regions for debugging/visualization
    manifest = struct( ...
        'id', {}, ...
        'region', {}, ...
        'coords', {}, ...
        'title', {}, ...
        'description', {});

    % Configuration tab entries
    manifest(end + 1) = make_entry('config_left', 'Configuration', cfg.coords.config.left, ...
        'Configuration Left Column', 'Method/grid/time/simulation/convergence/sustainability stacks');
    manifest(end + 1) = make_entry('config_right', 'Configuration', cfg.coords.config.right, ...
        'Configuration Right Column', 'Readiness, initial condition, and preview stacks');
    manifest(end + 1) = make_entry('config_method', 'Configuration', cfg.coords.config.panel_method, ...
        cfg.text.config_panels.method, 'Method and run-mode selector panel');
    manifest(end + 1) = make_entry('config_grid', 'Configuration', cfg.coords.config.panel_grid, ...
        cfg.text.config_panels.grid, 'Grid size and spatial-domain panel');
    manifest(end + 1) = make_entry('config_time', 'Configuration', cfg.coords.config.panel_time, ...
        cfg.text.config_panels.time, 'Time-step and viscosity panel');
    manifest(end + 1) = make_entry('config_sim', 'Configuration', cfg.coords.config.panel_sim, ...
        cfg.text.config_panels.simulation, 'Output/save/animation panel');
    manifest(end + 1) = make_entry('config_conv', 'Configuration', cfg.coords.config.panel_conv, ...
        cfg.text.config_panels.convergence, 'Convergence controls panel');
    manifest(end + 1) = make_entry('config_sus', 'Configuration', cfg.coords.config.panel_sus, ...
        cfg.text.config_panels.sustainability, 'Sustainability collectors and monitoring panel');
    manifest(end + 1) = make_entry('config_check', 'Configuration', cfg.coords.config.panel_check, ...
        cfg.text.config_panels.readiness, 'Readiness checks and launch controls');
    % Right column entries (readiness, IC setup, IC preview)
    manifest(end + 1) = make_entry('config_ic', 'Configuration', cfg.coords.config.panel_ic, ...
        cfg.text.config_panels.ic, 'Initial condition parameter panel');
    manifest(end + 1) = make_entry('config_preview', 'Configuration', cfg.coords.config.panel_preview, ...
        cfg.text.config_panels.preview, 'Initial condition visualization panel');

    % Live Monitor tab entries
    manifest(end + 1) = make_entry('monitor_left', 'Live Monitor', cfg.coords.monitor.left_panel, ...
        cfg.text.monitor_panels.dashboard, '8 plot tiles plus 1 numeric metrics tile');
    manifest(end + 1) = make_entry('monitor_sidebar', 'Live Monitor', cfg.coords.monitor.terminal_panel, ...
        cfg.text.monitor_panels.sidebar, 'Terminal log, run status, collector probes');

    % Results tab entries
    manifest(end + 1) = make_entry('results_figures', 'Results and Figures', cfg.coords.results.panel_fig, ...
        cfg.text.results_panels.figures, 'Generated figure browser and display');
    manifest(end + 1) = make_entry('results_metrics', 'Results and Figures', cfg.coords.results.panel_metrics, ...
        cfg.text.results_panels.metrics, 'Metrics summary readout');
end

function entry = make_entry(id, region, coords, title_txt, description_txt)
    % Helper function to create manifest entry struct
    entry = struct( ...
        'id', id, ...
        'region', region, ...
        'coords', coords, ...
        'title', title_txt, ...
        'description', description_txt);
end
