function Case = Boundary_Condition_Cases(X, Y, Boundary_Condition_Case)
%BOUNDARY_CONDITION_CASES  Return BC configuration struct for a named preset.
%
%   Case = Boundary_Condition_Cases(X, Y, Boundary_Condition_Case)
%
%   Inputs:
%     X, Y                    - meshgrid arrays of grid coordinates.
%     Boundary_Condition_Case - string key, one of:
%       'lid_driven_cavity'            (Case 1)
%       'driven_channel_flow'          (Case 2)
%       'lid_and_bottom_driven_cavity' (Case 3)
%       'enclosed_cavity'              (Case 4)
%       'periodic'                     (Case 5 - default for all solvers)
%       'user_defined'                 (Case 6 - individual UI selections)
%
%   Output struct fields:
%     .type, .description, .bc_top, .bc_bottom, .bc_left, .bc_right,
%     .U_top, .U_bottom, .omega_bc (function handle), .X, .Y

    % Helper: zero-vorticity on boundary rows/columns (no-slip approximation)
    noslip_bc = @(w, ~, ~) apply_noslip_bc(w);

    % Normalise the input key - accept type names or numeric aliases 1-6
    key = lower(strtrim(char(string(Boundary_Condition_Case))));
    key = regexprep(key, '^case[\s_]*', '');
    switch key
        case '1', key = 'lid_driven_cavity';
        case '2', key = 'driven_channel_flow';
        case '3', key = 'lid_and_bottom_driven_cavity';
        case '4', key = 'enclosed_cavity';
        case '5', key = 'periodic';
        case '6', key = 'user_defined';
    end

    switch key

        case 'lid_driven_cavity'
        % Case 1: All walls no-slip; top lid moves at +U0 in x-direction
            Case = struct( ...
                'type',        'lid_driven_cavity', ...
                'description', ['Enclosed cavity: no-slip on all walls, ' ...
                    'top lid moves at $+U_0$. Generates primary vortex beneath the lid.'], ...
                'bc_top',      'Neumann', ...
                'bc_bottom',   'Dirichlet', ...
                'bc_left',     'Dirichlet', ...
                'bc_right',    'Dirichlet', ...
                'U_top',       1.0, ...
                'U_bottom',    0.0, ...
                'omega_bc',    noslip_bc);

        case 'driven_channel_flow'
        % Case 2: Left/right periodic; top/bottom no-slip; top wall moves
            Case = struct( ...
                'type',        'driven_channel_flow', ...
                'description', ['Channel flow: top and bottom walls no-slip, left and right periodic. ' ...
                    'Top wall drives flow at $U_0$.'], ...
                'bc_top',      'Neumann', ...
                'bc_bottom',   'Dirichlet', ...
                'bc_left',     'Periodic', ...
                'bc_right',    'Periodic', ...
                'U_top',       1.0, ...
                'U_bottom',    0.0, ...
                'omega_bc',    noslip_bc);

        case 'lid_and_bottom_driven_cavity'
        % Case 3: Top and bottom both move (opposing), sides no-slip
            Case = struct( ...
                'type',        'lid_and_bottom_driven_cavity', ...
                'description', ['Opposing driven walls: top at $+U_0$, bottom at $-U_0$. ' ...
                    'Ideal for shear-layer and vortex-pair studies.'], ...
                'bc_top',      'Neumann', ...
                'bc_bottom',   'Neumann', ...
                'bc_left',     'Dirichlet', ...
                'bc_right',    'Dirichlet', ...
                'U_top',      +1.0, ...
                'U_bottom',   -1.0, ...
                'omega_bc',    noslip_bc);

        case 'enclosed_cavity'
        % Case 4: All walls no-slip, no driving velocity
            Case = struct( ...
                'type',        'enclosed_cavity', ...
                'description', ['Quiescent enclosed cavity: no-slip on all four walls. ' ...
                    'Vorticity set by initial condition only.'], ...
                'bc_top',      'Dirichlet', ...
                'bc_bottom',   'Dirichlet', ...
                'bc_left',     'Dirichlet', ...
                'bc_right',    'Dirichlet', ...
                'U_top',       0.0, ...
                'U_bottom',    0.0, ...
                'omega_bc',    noslip_bc);

        case 'periodic'
        % Case 5: Fully periodic - natural mode for all current solvers
            Case = struct( ...
                'type',        'periodic', ...
                'description', ['Fully periodic domain: all boundaries wrap around. ' ...
                    'Default for FD, Spectral, and FV solvers.'], ...
                'bc_top',      'Periodic', ...
                'bc_bottom',   'Periodic', ...
                'bc_left',     'Periodic', ...
                'bc_right',    'Periodic', ...
                'U_top',       0.0, ...
                'U_bottom',    0.0, ...
                'omega_bc',    @(w, ~, ~) w);

        case 'user_defined'
        % Case 6: Caller fills bc_top/bottom/left/right from UI selections
            Case = struct( ...
                'type',        'user_defined', ...
                'description', ['User-defined: each boundary set individually via the BC dropdowns.'], ...
                'bc_top',      'Periodic', ...
                'bc_bottom',   'Periodic', ...
                'bc_left',     'Periodic', ...
                'bc_right',    'Periodic', ...
                'U_top',       0.0, ...
                'U_bottom',    0.0, ...
                'omega_bc',    @(w, ~, ~) w);

        otherwise
            error('BoundaryConditionCases:UnknownCase', ...
                ['Unknown boundary condition case: ''%s''. ' ...
                 'Valid: lid_driven_cavity, driven_channel_flow, ' ...
                 'lid_and_bottom_driven_cavity, enclosed_cavity, ' ...
                 'periodic, user_defined (or numeric 1-6).'], key);
    end

    % Attach grid arrays for spatial omega_bc construction by callers
    Case.X = X;
    Case.Y = Y;
end

% =========================================================================
function omega = apply_noslip_bc(omega)
%APPLY_NOSLIP_BC  Zero-vorticity on boundary rows/columns (no-slip approx).
    if size(omega, 1) >= 2
        omega(1,   :) = 0;
        omega(end, :) = 0;
    end
    if size(omega, 2) >= 2
        omega(:,   1) = 0;
        omega(:, end) = 0;
    end
end