function params = create_default_parameters()
% CREATE_DEFAULT_PARAMETERS Factory function for simulation parameters
%
% Returns a struct with all default parameter values for tsunami vortex
% simulations. This provides a single source of truth for defaults.
%
% Usage:
%   params = create_default_parameters();
%   params.Nx = 256;  % Override specific values as needed
%
% Returns:
%   params - Struct with default simulation parameters
%
% Author: Analysis Framework
% Date: February 2026

    params = struct(...
        'default_method', 'FD', ...
        'default_mode', 'Evolution', ...
        'output_root', 'Results', ...
        'Lx', 10, ...
        'Ly', 10, ...
        'Nx', 128, ...
        'Ny', 128, ...
        'delta', 2, ...
        'use_explicit_delta', true, ...
        'nu', 1e-6, ...
        'dt', 0.01, ...
        'Tfinal', 8, ...
        't_final', 8, ...
        'num_plot_snapshots', 9, ...
        'num_snapshots', 9, ...
        'ic_type', "stretched_gaussian", ...
        'ic_coeff', [2, 0.2], ...
        'analysis_method', "Finite Difference", ...
        'method', "finite_difference", ...
        'method_config', [], ...
        'mode', "solve", ...
        'live_preview', false, ...
        'progress_stride', 0, ...
        'live_stride', 0, ...
        'create_animations', true, ...
        'animation_format', 'mp4', ...
        'animation_fps', 30, ...
        'animation_quality', 90, ...
        'animation_num_frames', 100, ...
        'num_animation_frames', 100, ...
        'animation_codec', 'MPEG-4', ...
        'animation_dir', [], ...
        'media', struct( ...
            'format', 'mp4', ...
            'codec', 'MPEG-4', ...
            'fps', 30, ...
            'num_frames', 100, ...
            'quality', 90, ...
            'fallback_format', 'gif'), ...
        'reporting', struct( ...
            'template', 'default', ...
            'template_by_mode', struct( ...
                'Evolution', 'evolution', ...
                'Convergence', 'convergence', ...
                'ParameterSweep', 'parameter_sweep', ...
                'Plotting', 'plotting')), ...
        'bathymetry_enabled', false, ...
        'bathymetry_file', '', ...
        'bathymetry_resolution', 1, ...
        'bathymetry_use_dry_mask', true, ...
        'energy_monitoring', struct('enabled', true, 'sample_interval', 0.5, 'output_dir', '../../sensor_logs'), ...
        'sustainability', struct( ...
            'enabled', true, ...
            'build_model', false, ...
            'auto_compare', false, ...
            'machine_tag', 'auto', ...
            'collector_paths', struct('cpuz', '', 'hwinfo', '', 'icue', '')));
    
    
    % Post-process derived fields
    params.t_final = params.Tfinal;
    params.num_snapshots = params.num_plot_snapshots;
    params.snap_times = linspace(0, params.Tfinal, params.num_plot_snapshots);
    params.plot_snap_times = params.snap_times;
    params.animation_times = linspace(0, params.Tfinal, params.num_animation_frames);
    
    % Ensure method and analysis_method are consistent
    if isstring(params.method) || ischar(params.method)
        method_lower = lower(char(params.method));
        switch method_lower
            case {'fd', 'finite_difference', 'finite difference'}
                params.method = 'finite_difference';
                params.analysis_method = 'Finite Difference';
            case {'spectral', 'fft', 'pseudospectral'}
                params.method = 'spectral';
                params.analysis_method = 'Spectral';
            case {'fv', 'finite_volume'}
                params.method = 'finite_volume';
                params.analysis_method = 'Finite Volume';
            case {'bathymetry', 'variable_bathymetry'}
                params.method = 'bathymetry';
                params.analysis_method = 'Variable Bathymetry';
            otherwise
                params.method = 'finite_difference';  % Default
                params.analysis_method = 'Finite Difference';
        end
    end
    
    % Method configuration defaults (self-contained, no external driver dependency)
    params.method_config = struct();
    params.method_config.fd = struct('advection_scheme', 'Arakawa', 'time_integrator', 'RK4');
    params.method_config.spectral = struct('dealiasing_rule', '2/3', 'time_integrator', 'RK4');
    params.method_config.fv = struct('reconstruction', 'MUSCL', 'flux', 'Roe', 'time_integrator', 'RK3');
    
    % Default animation_dir is resolved at runtime to canonical run Media path.
    params.animation_dir = '';
    
    % Visualization defaults - helper functions
    if exist('create_visualization_settings', 'file') == 2
        params.visualization = create_visualization_settings();
        params.plot_settings = create_plot_settings(params.visualization);
    end
end

function vis = create_visualization_settings()
% Default visualization settings
    vis = struct(...
        'contour_method', "contourf", ...
        'contour_levels', 25, ...
        'contour_colormap', "gray", ...
        'vector_method', "quiver", ...
        'vector_subsampling', 4, ...
        'vector_scale', 1.0, ...
        'colormap', "turbo");
end

function plot_set = create_plot_settings(visualization)
% Default plot formatting settings
    plot_set = struct(...
        'LineWidth', 1.5, ...
        'FontSize', 12, ...
        'MarkerSize', 8, ...
        'AxisLineWidth', 2.0, ...
        'ColorOrder', lines(7), ...
        'Grid', 'on', ...
        'Box', 'on', ...
        'Interpreter', 'latex', ...
        'Colormap', visualization.colormap);
end
